'use strict';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
const fmt=ms=>ms>0?`${Math.floor(ms/60000)}:${(ms/1000%60).toFixed(3).padStart(6,'0')}`:'미완료';
const date=t=>t?new Date(t).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'날짜 미확인';
const trackName=t=>({tsukuba_circuit:'쓰쿠바 서킷',deep_forest_raceway:'딥 포레스트 레이스웨이'})[t?.candidate?.id]||t?.candidate?.name||'코스 미확인';
let data,session,lap,reference,playing=false,lastTick=0,progress=0,project;
function node(tag,attrs={},parent){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(parent)parent.append(e);return e}
function text(parent,x,y,value,fill='#57635c',size=12){const e=node('text',{x,y,fill,'font-size':size},parent);e.textContent=value;return e}
function option(el,value,label){const e=document.createElement('option');e.value=value;e.textContent=label;el.append(e)}
function sessionCourse(s){const names=[...new Set(s.laps.filter(l=>l.track.status==='matched').map(l=>trackName(l.track)))];return s.course||names.join(' / ')||'코스 미확인'}
function prepare(l){let d=0;return l.trace.map((p,i)=>{if(i&&!p[6])d+=Math.hypot(p[1]-l.trace[i-1][1],p[2]-l.trace[i-1][2]);return {...p,d}})}
function samples(l){const points=prepare(l),max=points.at(-1)?.d||1;return points.map((p,i)=>({...p,f:l.training?.available?l.training.distanceTrace[i][0]/l.training.referenceLength:p.d/max}))}
function at(points,f){if(!points.length)return null;let i=points.findIndex(p=>p.f>=f);if(i<0)i=points.length-1;if(!i)return points[0];const a=points[i-1],b=points[i],r=(f-a.f)/(b.f-a.f||1);return Object.fromEntries([0,1,2,3,4,5].map(k=>[k,a[k]+r*(b[k]-a[k])]))}
function comparable(a,b){return a!==b&&a.comparable&&b.comparable&&a.carId===b.carId&&a.track.status==='matched'&&b.track.status==='matched'&&a.track.candidate.id===b.track.candidate.id&&Math.abs(a.distance-b.distance)/a.distance<.05}
function stop(){playing=false;$('play').textContent='▶ 재생'}
function chooseSession(i){stop();session=data.sessions[i];$('sessions').value=i;document.querySelectorAll('.session-item').forEach((b,j)=>b.classList.toggle('active',j===Number(i)));$('lap').replaceChildren();session.laps.forEach((l,j)=>option($('lap'),j,`${l.number}번 랩 · ${fmt(l.lapMs)}${l.comparable?'':' · 비교 제외'}`));$('session-note').textContent=`수신 ${Math.round(session.duration/60)}분 · ${session.packets.toLocaleString()}개 표본${session.truncated?' · 파일 끝부분 불완전':''}${session.invalid?' · 해독 실패 '+session.invalid+'개':''}${session.clockIsApproximate?' · 날짜는 파일명 기반 추정':''}`;let best=session.laps.reduce((a,l,j)=>l.comparable&&(a<0||l.lapMs<session.laps[a].lapMs)?j:a,-1);if(best<0)best=session.laps.findIndex(l=>l.trace.length>1);$('lap').value=best>=0?best:0;chooseLap()}
function chooseLap(){stop();lap=session.laps[Number($('lap').value)];$('reference').replaceChildren();option($('reference'),'','비교하지 않음');if(lap)session.laps.forEach((l,j)=>{if(comparable(lap,l))option($('reference'),j,`${l.number}번 랩 · ${fmt(l.lapMs)}`)});if($('reference').options.length>1)$('reference').selectedIndex=1;progress=0;$('position').value=0;render()}
function drawPath(svg,points,color,width=2,dash){if(!points.length)return;const d=points.map((p,i)=>`${!i||p.move?'M':'L'}${p.x.toFixed(2)},${p.y.toFixed(2)}`).join(' ');node('path',{d,fill:'none',stroke:color,'stroke-width':width,'stroke-linejoin':'round','stroke-linecap':'round',...(dash?{'stroke-dasharray':dash}:{})},svg)}
function map(){const svg=$('map');svg.replaceChildren();const trace=lap?.trace||[],ref=reference?.trace||[],base=lap?.track.referencePoints||[];const all=[...trace.map(p=>[p[1],p[2]]),...ref.map(p=>[p[1],p[2]]),...base];if(!all.length){text(svg,280,210,'분석할 주행 궤적이 없습니다');return}const xs=all.map(p=>p[0]),zs=all.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),scale=Math.min(700/(maxX-minX||1),335/(maxZ-minZ||1));const flip=$('mirror').checked?-1:1;project=(x,z)=>({x:400+(x-(maxX+minX)/2)*scale,y:210+flip*(z-(maxZ+minZ)/2)*scale});for(let x=0;x<800;x+=50)node('path',{d:`M${x},0 V430`,stroke:'#e8ede8'},svg);for(let y=0;y<430;y+=50)node('path',{d:`M0,${y} H800`,stroke:'#e8ede8'},svg);drawPath(svg,base.map(p=>project(...p)),'#a3afa6',2,'5 6');drawPath(svg,ref.map(p=>({...project(p[1],p[2]),move:p[6]})),'#795898',3);drawPath(svg,trace.map(p=>({...project(p[1],p[2]),move:p[6]})),'#2f7d5a',2.5);if(trace.length){const p=project(trace[0][1],trace[0][2]);text(svg,p.x+9,p.y-10,lap.startObserved?'START':'기록 시작','#17201c',11);for(const f of [.12,.37,.62,.87]){let i=Math.floor(f*(trace.length-2)),a=project(trace[i][1],trace[i][2]),b=project(trace[i+1][1],trace[i+1][2]),angle=Math.atan2(b.y-a.y,b.x-a.x);node('path',{d:'M-8,-5 L0,0 L-8,5',fill:'none',stroke:'#2f7d5a','stroke-width':2.5,transform:`translate(${a.x} ${a.y}) rotate(${angle*180/Math.PI})`},svg)}}node('circle',{id:'cursor',r:6,fill:'#fff',stroke:'#f6f8f6','stroke-width':3},svg);$('map-note').textContent=$('mirror').checked?'진단용 반전 화면입니다. 원본 데이터와 코스 판정은 바뀌지 않습니다.':'GT7 X/Z 좌표: +X 오른쪽, +Z 아래쪽. 회전만 다른 공식 지도와 비교할 수 있습니다.';drawTrainingMarkers()}
function chart(){const svg=$('charts');svg.replaceChildren();if(!lap)return;const a=samples(lap),b=reference?samples(reference):[];const max=Math.max(100,...a.map(p=>p[3]),...b.map(p=>p[3]))*1.05;for(const y of [35,100,160,210,265])node('path',{d:`M55 ${y} H785`,stroke:'#d6ded8'},svg);text(svg,2,30,'km/h');text(svg,4,100,Math.round(max/2));text(svg,6,160,'0');text(svg,4,211,'가속');text(svg,4,266,'제동');text(svg,55,287,'0%');text(svg,740,287,'100%');for(const [arr,color] of [[b,'#795898'],[a,'#2f7d5a']]){drawPath(svg,arr.map(p=>({x:55+p.f*730,y:160-p[3]/max*125,move:p[6]})),color,2);for(const [k,base] of [[4,210],[5,265]])drawPath(svg,arr.map(p=>({x:55+p.f*730,y:base-p[k]*35,move:p[6]})),color,1.5)}node('path',{id:'chart-cursor',d:'M55 25 V265',stroke:'#57635c','stroke-width':1,'stroke-dasharray':'4 4'},svg)}
function cursor(){const p=lap?at(samples(lap),progress):null;$('progress').textContent=Math.round(progress*100)+'%';if(p&&project&&$('cursor')){const q=project(p[1],p[2]);$('cursor').setAttribute('cx',q.x);$('cursor').setAttribute('cy',q.y);$('cursor-values').textContent=`선택 랩 ${p[0].toFixed(1)}초 · ${p[3].toFixed(1)} km/h · 가속 ${Math.round(p[4]*100)}% · 제동 ${Math.round(p[5]*100)}%`}else $('cursor-values').textContent='';if($('chart-cursor'))$('chart-cursor').setAttribute('d',`M${55+progress*730} 25 V265`)}
function render(){reference=$('reference').value!==''?session.laps[Number($('reference').value)]:null;const t=lap?.track;$('course').textContent=session.course||((t?.status==='matched'||t?.status==='ambiguous')?trackName(t):sessionCourse(session));$('course-status').textContent=session.course?'사용자 입력':t?.status==='matched'?'기준 궤적 일치 · 추정':t?.status==='ambiguous'?'후보 중복':'미확정';$('car').textContent=lap?.car||'유효한 주행 랩 없음';$('lap-time').textContent=lap?fmt(lap.lapMs):'—';$('delta').textContent=reference?`${((lap.lapMs-reference.lapMs)/1000).toFixed(3)}초`:'—';$('delta').className=reference&&lap.lapMs<reference.lapMs?'gain':'';$('speed').textContent=lap?.maxKph?`${lap.maxKph.toFixed(1)} km/h`:'—';$('lap-note').textContent=!lap?'메뉴·대기 표본만 있는 기록입니다.':lap.comparable?'시작·완료가 관측되고 연속성 검사를 통과한 랩입니다.':`비교 제외: ${!lap.completed?'미완료 랩':!lap.startObserved?'시작선 관측 없음':lap.interrupted?'수신 누락·일시정지·상태 변경':'궤적 연속성 또는 시간 범위 부족'}. 수신된 완료 시간은 보존합니다.`;$('sections').replaceChildren();if(reference){const diffs=lap.sections.map((v,i)=>v-reference.sections[i]);const worst=Math.max(...diffs),index=diffs.indexOf(worst);$('insight').textContent=`비교 랩보다 ${Math.abs((lap.lapMs-reference.lapMs)/1000).toFixed(3)}초 ${lap.lapMs<reference.lapMs?'빨랐습니다':'느렸습니다'}. ${worst>.01?`추정 구간 ${index+1}에서 ${worst.toFixed(2)}초 더 걸렸습니다. 해당 구간의 속도와 페달을 함께 확인해 보세요.`:'모든 추정 구간에서 비교 랩과 같거나 빨랐습니다.'}`;diffs.forEach((v,i)=>{const e=document.createElement('button');e.className=`section ${v<=0?'gain':'loss'}`;e.textContent=`${i+1}`;const b=document.createElement('b');b.textContent=`${v>0?'+':''}${v.toFixed(2)}`;e.append(b);e.title=`구간 ${i+1}: ${v.toFixed(2)}초 차이`;e.onclick=()=>{const own=prepare(lap),total=own.at(-1)?.d||1,k=own.findIndex(p=>p.d/total>=(i+.5)/10);progress=lap.training?.available?lap.training.distanceTrace[Math.max(0,k)][0]/lap.training.referenceLength:(i+.5)/10;$('position').value=progress*1000;cursor()};$('sections').append(e)})}else $('insight').textContent='같은 차량·식별 코스에서 비교 가능한 랩을 선택하면 구간별 시간 차이를 표시합니다. 불완전한 랩의 손익은 계산하지 않습니다.';const audit=$('track-audit');audit.replaceChildren();const p=document.createElement('p');p.textContent=t?.coordinateCheck?`기준 궤적 거리 오차(RMSE): ${t.coordinateCheck.directRmse}m · 좌우 반전 가설: ${t.coordinateCheck.mirrorXRmse}m. ${t.coordinateCheck.verdict} 기준 자료: ${t.candidate.referenceDate.slice(0,10)}.`:(t?.reason||'완주 랩이 없습니다.');audit.append(p);renderTraining();map();chart();cursor()}
$('sessions').onchange=e=>chooseSession(e.target.value);$('lap').onchange=chooseLap;$('reference').onchange=render;$('mirror').onchange=()=>{map();cursor()};$('position').oninput=e=>{progress=e.target.value/1000;cursor()};$('play').onclick=()=>{if(!lap?.trace.length)return;playing=!playing;$('play').textContent=playing?'Ⅱ 일시정지':'▶ 재생';lastTick=performance.now();if(progress>=1)progress=0};function tick(now){if(playing&&lap){const pts=samples(lap),current=at(pts,progress),target=(current?.[0]||0)+(now-lastTick)/1000;let j=pts.findIndex(p=>p[0]>=target);if(j<0)progress=1;else if(j===0)progress=pts[0].f;else{const a=pts[j-1],b=pts[j];progress=a.f+(b.f-a.f)*(target-a[0])/(b[0]-a[0]||1)}$('position').value=progress*1000;cursor();if(progress>=1)stop()}lastTick=now;requestAnimationFrame(tick)}requestAnimationFrame(tick);
fetch('data.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('기록을 불러오지 못했습니다.');return r.json()}).then(d=>{data=d;if(!d.sessions.length)throw Error('아직 게시된 주행 기록이 없습니다.');const laps=d.sessions.flatMap(s=>s.laps);$('session-count').textContent=d.sessions.length;$('lap-count').textContent=laps.filter(l=>l.completed&&l.lapMs>0).length;$('clean-count').textContent=laps.filter(l=>l.comparable).length;$('track-count').textContent=new Set(laps.filter(l=>l.track.status==='matched').map(l=>l.track.candidate.id)).size;$('updated').textContent=`최근 반영 ${date(d.updatedAt)}`;d.sessions.forEach((s,i)=>{option($('sessions'),i,`${date(s.startedAt)} · ${sessionCourse(s)}`);const b=document.createElement('button');b.className='session-item';b.textContent=date(s.startedAt);const small=document.createElement('small');small.textContent=sessionCourse(s);b.append(small);b.onclick=()=>chooseSession(i);$('session-list').append(b)});chooseSession(0)}).catch(e=>{$('error').hidden=false;$('error').textContent=e.message;$('updated').textContent='기록 불러오기 실패';});
