window.DRILLS=(window.DRILLS||[]).concat([
  {
    "id": 21,
    "part": "PART 3",
    "partTitle": "조건과 판단",
    "title": "비교 연산자",
    "goal": "값을 비교해 bool 결과를 만든다.",
    "concept": "<code>== != &lt; &gt; &lt;= &gt;=</code>는 두 값을 비교해 true/false를 만듭니다. <code>=</code> 대입과 <code>==</code> 비교를 구분하세요.",
    "code": "#include <iostream>\nint main() {\n    int speed = 100;\n    std::cout << std::boolalpha\n              << (speed >= 100) << \"\\n\";\n}",
    "breakIt": "`>=`를 `>`로 바꾸고 speed가 정확히 100일 때 차이를 보세요.",
    "observe": "조건식이 true/false 중 무엇이 되는지 값의 경계에서 확인하세요.",
    "challenge": "lapTime 62.3이 target 63.0보다 빠른지 bool로 출력하세요.",
    "hint": "랩타임은 값이 작을수록 빠릅니다.",
    "answer": "#include <iostream>\nint main() {\n    double lapTime=62.3, target=63.0;\n    std::cout << std::boolalpha << (lapTime < target) << \"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 22,
    "part": "PART 3",
    "partTitle": "조건과 판단",
    "title": "if",
    "goal": "조건이 참일 때만 코드를 실행한다.",
    "concept": "<code>if (조건)</code>은 조건이 true일 때 중괄호 안의 코드를 실행합니다.",
    "code": "#include <iostream>\nint main() {\n    int speed = 130;\n    if (speed > 120) {\n        std::cout << \"FAST\\n\";\n    }\n}",
    "breakIt": "speed를 120으로 바꾸고 `>`와 `>=`의 차이를 확인하세요.",
    "observe": "조건식이 true/false 중 무엇이 되는지 값의 경계에서 확인하세요.",
    "challenge": "fuel이 10보다 작을 때 `LOW FUEL`을 출력하세요.",
    "hint": "조건식은 `fuel < 10.0`입니다.",
    "answer": "#include <iostream>\nint main() {\n    double fuel=8.0;\n    if (fuel < 10.0) {\n        std::cout << \"LOW FUEL\\n\";\n    }\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 23,
    "part": "PART 3",
    "partTitle": "조건과 판단",
    "title": "if / else",
    "goal": "두 갈래 중 하나를 선택한다.",
    "concept": "<code>else</code>는 if 조건이 거짓일 때 실행됩니다. 둘 중 정확히 한 경로가 실행됩니다.",
    "code": "#include <iostream>\nint main() {\n    int speed=80;\n    if (speed >= 100) std::cout << \"FAST\\n\";\n    else std::cout << \"NORMAL\\n\";\n}",
    "breakIt": "speed를 99, 100, 101로 바꿔 경계를 확인하세요.",
    "observe": "조건식이 true/false 중 무엇이 되는지 값의 경계에서 확인하세요.",
    "challenge": "lapTime이 60초 미만이면 `GOLD`, 아니면 `KEEP PRACTICING`을 출력하세요.",
    "hint": "if/else 두 경로를 만드세요.",
    "answer": "#include <iostream>\nint main() {\n    double lapTime=59.8;\n    if (lapTime < 60.0) std::cout << \"GOLD\\n\";\n    else std::cout << \"KEEP PRACTICING\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 24,
    "part": "PART 3",
    "partTitle": "조건과 판단",
    "title": "else if",
    "goal": "여러 구간을 순서대로 분류한다.",
    "concept": "<code>else if</code>를 사용하면 여러 조건 중 첫 번째로 참인 경로 하나를 선택합니다. 조건의 순서가 중요합니다.",
    "code": "#include <iostream>\nint main() {\n    int speed=115;\n    if (speed >= 140) std::cout << \"VERY FAST\\n\";\n    else if (speed >= 100) std::cout << \"FAST\\n\";\n    else std::cout << \"NORMAL\\n\";\n}",
    "breakIt": "첫 조건을 `speed >= 100`으로 바꿔 150을 넣어 보세요. 더 넓은 조건을 먼저 두면 어떤 문제가 생기는지 봅니다.",
    "observe": "조건식이 true/false 중 무엇이 되는지 값의 경계에서 확인하세요.",
    "challenge": "점수 90 이상 A, 80 이상 B, 70 이상 C, 나머지 D를 출력하세요.",
    "hint": "큰 경계부터 내려오세요.",
    "answer": "#include <iostream>\nint main() {\n    int score=84;\n    if(score>=90) std::cout<<\"A\\n\";\n    else if(score>=80) std::cout<<\"B\\n\";\n    else if(score>=70) std::cout<<\"C\\n\";\n    else std::cout<<\"D\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 25,
    "part": "PART 3",
    "partTitle": "조건과 판단",
    "title": "논리 연산자",
    "goal": "여러 조건을 &&, ||, !로 결합한다.",
    "concept": "<code>&amp;&amp;</code>는 둘 다 참, <code>||</code>는 하나 이상 참, <code>!</code>는 참/거짓을 뒤집습니다.",
    "code": "#include <iostream>\nint main() {\n    int speed=90;\n    bool rain=true;\n    if (rain && speed > 80) {\n        std::cout << \"SLOW DOWN\\n\";\n    }\n}",
    "breakIt": "&&를 ||로 바꾸고 rain/speed 값을 여러 조합으로 바꿔 보세요.",
    "observe": "조건식이 true/false 중 무엇이 되는지 값의 경계에서 확인하세요.",
    "challenge": "fuel이 10 미만이거나 tireWear가 80 초과면 `PIT`을 출력하세요.",
    "hint": "두 조건을 ||로 연결하세요.",
    "answer": "#include <iostream>\nint main() {\n    double fuel=8;\n    int tireWear=50;\n    if (fuel < 10 || tireWear > 80) std::cout << \"PIT\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 26,
    "part": "PART 3",
    "partTitle": "조건과 판단",
    "title": "중첩 if",
    "goal": "조건 안에서 추가 조건을 판단한다.",
    "concept": "if 안에 또 if를 둘 수 있습니다. 다만 지나치게 깊은 중첩은 읽기 어려우므로 논리 연산자로 단순화할 수 있는지도 생각하세요.",
    "code": "#include <iostream>\nint main() {\n    bool engineOn=true;\n    int gear=1;\n    if (engineOn) {\n        if (gear==1) std::cout << \"READY\\n\";\n    }\n}",
    "breakIt": "engineOn=false, gear=1과 engineOn=true, gear=2를 각각 시험하세요.",
    "observe": "조건식이 true/false 중 무엇이 되는지 값의 경계에서 확인하세요.",
    "challenge": "engineOn이 true이고 brake가 true일 때만 `SAFE TO SHIFT`를 출력하세요. 중첩 if로 먼저 작성하세요.",
    "hint": "바깥에서 engineOn, 안쪽에서 brake를 검사합니다.",
    "answer": "#include <iostream>\nint main() {\n    bool engineOn=true, brake=true;\n    if(engineOn) {\n        if(brake) std::cout<<\"SAFE TO SHIFT\\n\";\n    }\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 27,
    "part": "PART 3",
    "partTitle": "조건과 판단",
    "title": "switch",
    "goal": "정수·열거형 값에 따라 여러 분기를 만든다.",
    "concept": "<code>switch</code>는 하나의 값에 대해 여러 case를 선택할 때 읽기 좋습니다. 일반적으로 각 case 끝의 <code>break</code>를 의식하세요.",
    "code": "#include <iostream>\nint main() {\n    int gear=3;\n    switch(gear) {\n        case 1: std::cout<<\"LOW\\n\"; break;\n        case 2: std::cout<<\"MID\\n\"; break;\n        case 3: std::cout<<\"HIGH\\n\"; break;\n        default: std::cout<<\"OTHER\\n\";\n    }\n}",
    "breakIt": "case 2의 break를 지우고 gear=2로 실행해 fall-through를 관찰하세요.",
    "observe": "조건식이 true/false 중 무엇이 되는지 값의 경계에서 확인하세요.",
    "challenge": "1=Practice, 2=Race, 3=Time Trial을 출력하는 menu switch를 만드세요.",
    "hint": "각 case 뒤에 break를 넣으세요.",
    "answer": "#include <iostream>\nint main() {\n    int menu=3;\n    switch(menu) {\n        case 1: std::cout<<\"Practice\\n\"; break;\n        case 2: std::cout<<\"Race\\n\"; break;\n        case 3: std::cout<<\"Time Trial\\n\"; break;\n        default: std::cout<<\"Unknown\\n\";\n    }\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 28,
    "part": "PART 3",
    "partTitle": "조건과 판단",
    "title": "조건 연산자 ?:",
    "goal": "간단한 두 값 선택을 한 표현식으로 쓴다.",
    "concept": "<code>조건 ? 값1 : 값2</code>는 조건에 따라 두 값 중 하나를 선택하는 표현식입니다. 복잡한 로직에는 if가 더 읽기 좋습니다.",
    "code": "#include <iostream>\nint main() {\n    int speed=110;\n    const char* label = speed>=100 ? \"FAST\" : \"NORMAL\";\n    std::cout << label << \"\\n\";\n}",
    "breakIt": "조건을 반대로 바꾸고 두 문자열은 그대로 두어 결과가 어떻게 뒤집히는지 보세요.",
    "observe": "조건식이 true/false 중 무엇이 되는지 값의 경계에서 확인하세요.",
    "challenge": "lapTime < 60이면 `PASS`, 아니면 `RETRY`를 선택해 출력하세요.",
    "hint": "문자열을 선택하는 삼항 연산식을 만드세요.",
    "answer": "#include <iostream>\nint main() {\n    double lapTime=60.4;\n    std::cout << (lapTime<60 ? \"PASS\" : \"RETRY\") << \"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 29,
    "part": "PART 3",
    "partTitle": "조건과 판단",
    "title": "입력 검증",
    "goal": "잘못된 입력을 조건으로 걸러낸다.",
    "concept": "프로그램은 정상 입력만 온다고 가정하면 약합니다. 값의 범위를 검사하고 잘못된 경우 명확히 처리하세요.",
    "code": "#include <iostream>\nint main() {\n    int gear=0;\n    std::cin >> gear;\n    if (gear < 1 || gear > 6) {\n        std::cout << \"INVALID GEAR\\n\";\n    } else {\n        std::cout << \"OK\\n\";\n    }\n}",
    "breakIt": "조건의 ||를 &&로 바꿔 왜 잘못된 검사가 되는지 확인하세요.",
    "observe": "조건식이 true/false 중 무엇이 되는지 값의 경계에서 확인하세요.",
    "challenge": "throttle을 0~100으로 입력받아 범위를 벗어나면 `INVALID`를 출력하세요.",
    "hint": "0 미만 또는 100 초과를 검사합니다.",
    "answer": "#include <iostream>\nint main() {\n    double throttle=0;\n    std::cin>>throttle;\n    if(throttle<0 || throttle>100) std::cout<<\"INVALID\\n\";\n    else std::cout<<\"OK\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 30,
    "part": "PART 3",
    "partTitle": "조건과 판단",
    "title": "속도 분류기",
    "goal": "조건문을 작은 실제 문제에 적용한다.",
    "concept": "경계값을 명확히 정의하고 큰 값부터 검사하면 구간 분류가 읽기 쉬워집니다.",
    "code": "#include <iostream>\nint main() {\n    int speed=0;\n    std::cin>>speed;\n    if(speed>=160) std::cout<<\"EXTREME\\n\";\n    else if(speed>=120) std::cout<<\"FAST\\n\";\n    else if(speed>=60) std::cout<<\"CRUISE\\n\";\n    else std::cout<<\"SLOW\\n\";\n}",
    "breakIt": "120, 159, 160을 입력해 각 경계가 의도대로 분류되는지 확인하세요.",
    "observe": "조건식이 true/false 중 무엇이 되는지 값의 경계에서 확인하세요.",
    "challenge": "브레이크 압력 80 이상 HARD, 40 이상 MEDIUM, 0 초과 LIGHT, 0이면 NONE으로 분류하세요.",
    "hint": "큰 값부터 else if로 내려오세요.",
    "answer": "#include <iostream>\nint main() {\n    int brake=0; std::cin>>brake;\n    if(brake>=80) std::cout<<\"HARD\\n\";\n    else if(brake>=40) std::cout<<\"MEDIUM\\n\";\n    else if(brake>0) std::cout<<\"LIGHT\\n\";\n    else std::cout<<\"NONE\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  }
]);