window.DRILLS=(window.DRILLS||[]).concat([
  {
    "id": 96,
    "part": "PART 10",
    "partTitle": "GT7 텔레메트리 미니 프로젝트",
    "title": "브레이킹 이벤트 찾기",
    "goal": "연속 샘플에서 상태 변화 시점을 찾는다.",
    "concept": "텔레메트리는 개별 값보다 <strong>변화</strong>가 중요합니다. 이전 샘플과 현재 샘플을 비교하면 브레이크 시작 같은 이벤트를 찾을 수 있습니다.",
    "code": "#include <iostream>\n#include <vector>\nstruct S{double time,brake;};\nint main(){\n    std::vector<S>d{{0.0,0},{0.1,0},{0.2,15},{0.3,60}};\n    for(std::size_t i=1;i<d.size();++i)\n        if(d[i-1].brake==0 && d[i].brake>0)\n            std::cout<<\"Brake starts at \"<<d[i].time<<\" s\\n\";\n}",
    "breakIt": "이전 샘플 검사를 빼면 브레이크 중인 모든 샘플이 이벤트처럼 잡히는지 보세요.",
    "observe": "문법보다 입력 → 구조화 → 계산 → 출력의 전체 데이터 흐름을 추적하세요.",
    "challenge": "브레이크가 0으로 돌아오는 release 시점도 찾으세요.",
    "hint": "이전 brake>0 && 현재 brake==0을 검사합니다.",
    "answer": "#include <iostream>\n#include <vector>\nstruct S{double time,brake;};\nint main(){\n    std::vector<S>d{{0,0},{.1,20},{.2,60},{.3,0}};\n    for(std::size_t i=1;i<d.size();++i){\n        if(d[i-1].brake==0&&d[i].brake>0) std::cout<<\"start \"<<d[i].time<<\"\\n\";\n        if(d[i-1].brake>0&&d[i].brake==0) std::cout<<\"release \"<<d[i].time<<\"\\n\";\n    }\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 97,
    "part": "PART 10",
    "partTitle": "GT7 텔레메트리 미니 프로젝트",
    "title": "스로틀·브레이크 겹침",
    "goal": "두 입력이 동시에 큰 구간을 탐지한다.",
    "concept": "규칙을 수치 조건으로 정의하면 텔레메트리에서 특정 주행 패턴을 자동 탐지할 수 있습니다. 임계값은 학습용 예시입니다.",
    "code": "#include <iostream>\n#include <vector>\nstruct S{double time,throttle,brake;};\nint main(){\n    std::vector<S>d{{0,80,0},{.1,70,30},{.2,20,80}};\n    for(const auto& s:d)\n        if(s.throttle>50 && s.brake>20)\n            std::cout<<\"overlap at \"<<s.time<<\"\\n\";\n}",
    "breakIt": "&&를 ||로 바꿔 탐지 의미가 얼마나 달라지는지 보세요.",
    "observe": "문법보다 입력 → 구조화 → 계산 → 출력의 전체 데이터 흐름을 추적하세요.",
    "challenge": "overlap 샘플 개수와 전체 대비 비율을 계산하세요.",
    "hint": "count를 증가시키고 data.size()로 나눕니다.",
    "answer": "#include <iostream>\n#include <vector>\nstruct S{double throttle,brake;};\nint main(){\n    std::vector<S>d{{80,0},{70,30},{20,80},{60,40}};\n    int count=0;\n    for(const auto&s:d) if(s.throttle>50&&s.brake>20) ++count;\n    double ratio=100.0*count/d.size();\n    std::cout<<count<<\" samples, \"<<ratio<<\"%\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 98,
    "part": "PART 10",
    "partTitle": "GT7 텔레메트리 미니 프로젝트",
    "title": "TelemetryAnalyzer 클래스",
    "goal": "분석 기능을 하나의 객체로 묶는다.",
    "concept": "데이터와 관련 분석 함수를 클래스로 묶으면 책임이 명확해집니다. 외부에는 필요한 인터페이스만 공개합니다.",
    "code": "#include <iostream>\n#include <utility>\n#include <vector>\nstruct Sample{double speed;};\nclass TelemetryAnalyzer {\n    std::vector<Sample> data_;\npublic:\n    explicit TelemetryAnalyzer(std::vector<Sample> d):data_(std::move(d)){}\n    double averageSpeed() const {\n        if(data_.empty()) return 0;\n        double sum=0; for(const auto&s:data_) sum+=s.speed;\n        return sum/data_.size();\n    }\n};\nint main(){\n    TelemetryAnalyzer a({{100},{120},{140}});\n    std::cout<<a.averageSpeed()<<\"\\n\";\n}",
    "breakIt": "data_를 public으로 바꿨을 때 외부가 내부 상태를 마음대로 바꿀 수 있는 설계 차이를 생각하세요.",
    "observe": "문법보다 입력 → 구조화 → 계산 → 출력의 전체 데이터 흐름을 추적하세요.",
    "challenge": "maxSpeed() const 멤버 함수를 추가하세요.",
    "hint": "Drill 93의 로직을 data_에 적용합니다.",
    "answer": "#include <iostream>\n#include <utility>\n#include <vector>\nstruct Sample{double speed;};\nclass TelemetryAnalyzer{\n    std::vector<Sample> data_;\npublic:\n    explicit TelemetryAnalyzer(std::vector<Sample>d):data_(std::move(d)){}\n    double maxSpeed() const{\n        if(data_.empty()) return 0;\n        double m=data_.front().speed;\n        for(const auto&s:data_) if(s.speed>m)m=s.speed;\n        return m;\n    }\n};\nint main(){TelemetryAnalyzer a({{100},{150},{120}});std::cout<<a.maxSpeed()<<\"\\n\";}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 99,
    "part": "PART 10",
    "partTitle": "GT7 텔레메트리 미니 프로젝트",
    "title": "다중 파일 CLI 분석기",
    "goal": "헤더·구현·main을 실제 프로젝트로 분리한다.",
    "concept": "프로젝트가 커지면 모델/분석 로직/입출력을 분리합니다. main은 ‘무엇을 할지’를 보여주고 세부 계산은 다른 파일이 맡게 합니다.",
    "code": "telemetry/\n├── Telemetry.h\n├── Telemetry.cpp\n├── main.cpp\n└── telemetry.csv\n\n// build:\n// clang++ -std=c++20 main.cpp Telemetry.cpp -o telemetry",
    "breakIt": "Telemetry.cpp를 빌드 명령에서 빼 링크 오류를 확인하세요.",
    "observe": "한 파일짜리 코드를 세 책임으로 나누고 다시 링크하는 것이 핵심입니다.",
    "challenge": "Telemetry.h에 Sample과 Analyzer 선언, Telemetry.cpp에 averageSpeed 정의, main.cpp에 사용 코드를 실제로 나누세요.",
    "hint": "Drill 71~73과 98을 합치는 작업입니다.",
    "answer": "// Telemetry.h\n#pragma once\n#include <vector>\nstruct Sample{double speed;};\nclass Analyzer{\n    std::vector<Sample> data_;\npublic:\n    explicit Analyzer(std::vector<Sample> d);\n    double averageSpeed() const;\n};\n\n// main.cpp에서는 #include \"Telemetry.h\" 후 Analyzer를 사용",
    "compile": "clang++ -std=c++20 main.cpp Telemetry.cpp -o telemetry && ./telemetry"
  },
  {
    "id": 100,
    "part": "PART 10",
    "partTitle": "GT7 텔레메트리 미니 프로젝트",
    "title": "FINAL · GT7 Telemetry Analyzer",
    "goal": "100개 Drill을 작은 분석 프로그램으로 통합한다.",
    "concept": "최종 목표는 거대한 앱이 아니라 <strong>데이터 모델 → 파일 입력 → 분석 → 결과 출력</strong>의 전체 파이프라인을 스스로 구성하는 것입니다. 다음 단계에서 실제 GT7 UDP 수신으로 확장할 수 있습니다.",
    "code": "// telemetry.csv: time,speed,throttle,brake\n#include <fstream>\n#include <iostream>\n#include <sstream>\n#include <string>\n#include <vector>\n\nstruct Sample { double time,speed,throttle,brake; };\n\nSample parse(const std::string& line){\n    std::stringstream ss(line);\n    std::string a,b,c,d;\n    std::getline(ss,a,','); std::getline(ss,b,',');\n    std::getline(ss,c,','); std::getline(ss,d,',');\n    return {std::stod(a),std::stod(b),std::stod(c),std::stod(d)};\n}\n\nint main(){\n    std::ifstream in(\"telemetry.csv\");\n    if(!in){ std::cerr<<\"cannot open telemetry.csv\\n\"; return 1; }\n    std::vector<Sample> data;\n    std::string line;\n    while(std::getline(in,line))\n        if(!line.empty()) data.push_back(parse(line));\n    if(data.empty()){ std::cout<<\"no data\\n\"; return 0; }\n\n    double sum=0,maxSpeed=data.front().speed;\n    int brakeEvents=0;\n    for(std::size_t i=0;i<data.size();++i){\n        sum+=data[i].speed;\n        if(data[i].speed>maxSpeed) maxSpeed=data[i].speed;\n        if(i>0 && data[i-1].brake==0 && data[i].brake>0) ++brakeEvents;\n    }\n    std::cout<<\"samples: \"<<data.size()<<\"\\n\";\n    std::cout<<\"avg speed: \"<<sum/data.size()<<\"\\n\";\n    std::cout<<\"max speed: \"<<maxSpeed<<\"\\n\";\n    std::cout<<\"brake events: \"<<brakeEvents<<\"\\n\";\n}",
    "breakIt": "CSV 한 줄을 일부러 잘못 만들고 파일 이름도 틀리게 해 입력 오류가 어디서 드러나는지 확인하세요.",
    "observe": "정답은 하나의 코드가 아니라 체크리스트를 스스로 만족시키는 프로젝트입니다. 먼저 동작하게 만든 뒤 구조를 개선하세요.",
    "challenge": "최종 프로그램을 3개 이상 파일로 분리하고 overlap ratio, brake start times, max speed를 모두 출력하세요. README에 빌드 방법과 CSV 형식도 적으세요.",
    "hint": "Sample/파싱은 Telemetry.*, 분석은 Analyzer.*, main은 파일 경로와 출력만 담당하게 나누면 좋습니다.",
    "answer": "// 완성 기준\n// [ ] telemetry.csv를 읽는다.\n// [ ] Sample 객체로 변환한다.\n// [ ] 평균/최고 속도를 계산한다.\n// [ ] 브레이크 시작 이벤트를 찾는다.\n// [ ] throttle/brake overlap 비율을 계산한다.\n// [ ] 잘못된 파일 경로를 처리한다.\n// [ ] 헤더와 .cpp로 역할을 분리한다.\n// [ ] C++20으로 빌드된다.\n//\n// 다음 단계:\n// 실제 GT7 UDP 패킷 -> Sample -> 실시간 Analyzer",
    "compile": "clang++ -std=c++20 main.cpp -o gt7_analyzer && ./gt7_analyzer"
  }
]);