window.DRILLS=(window.DRILLS||[]).concat([
  {
    "id": 11,
    "part": "PART 2",
    "partTitle": "변수 · 자료형 · 연산",
    "title": "int",
    "goal": "정수형 변수를 선언·초기화·변경한다.",
    "concept": "<code>int</code>는 정수를 저장합니다. 변수는 이름을 가진 저장 공간으로 생각하면 됩니다.",
    "code": "#include <iostream>\nint main() {\n    int lap = 1;\n    lap = lap + 1;\n    std::cout << lap << \"\\n\";\n}",
    "breakIt": "int 선언을 지우고 lap을 사용해 보세요.",
    "observe": "타입과 값이 어떻게 달라졌는지 출력 결과와 컴파일 메시지를 함께 확인하세요.",
    "challenge": "gear를 1로 시작해 두 번 증가시켜 3을 출력하세요.",
    "hint": "`++gear;`를 사용할 수 있습니다.",
    "answer": "#include <iostream>\nint main() {\n    int gear = 1;\n    ++gear;\n    ++gear;\n    std::cout << gear << \"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 12,
    "part": "PART 2",
    "partTitle": "변수 · 자료형 · 연산",
    "title": "double",
    "goal": "소수 값을 저장하고 계산한다.",
    "concept": "<code>double</code>은 랩타임·거리·온도처럼 소수점이 필요한 값을 다룰 때 널리 씁니다.",
    "code": "#include <iostream>\nint main() {\n    double lapTime = 62.347;\n    double delta = 0.215;\n    std::cout << lapTime - delta << \"\\n\";\n}",
    "breakIt": "double을 int로 바꿔 소수 부분이 어떻게 되는지 보세요.",
    "observe": "타입과 값이 어떻게 달라졌는지 출력 결과와 컴파일 메시지를 함께 확인하세요.",
    "challenge": "100.0 km를 1.25시간에 달렸을 때 평균속도를 계산하세요.",
    "hint": "distance / hours 입니다.",
    "answer": "#include <iostream>\nint main() {\n    double distance = 100.0;\n    double hours = 1.25;\n    std::cout << distance / hours << \" km/h\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 13,
    "part": "PART 2",
    "partTitle": "변수 · 자료형 · 연산",
    "title": "char",
    "goal": "문자 하나를 저장한다.",
    "concept": "<code>char</code>는 문자 하나를 저장하며 문자 리터럴에는 작은따옴표를 사용합니다.",
    "code": "#include <iostream>\nint main() {\n    char grade = 'A';\n    std::cout << grade << \"\\n\";\n}",
    "breakIt": "작은따옴표를 없애 `A`만 남기고 컴파일해 보세요.",
    "observe": "타입과 값이 어떻게 달라졌는지 출력 결과와 컴파일 메시지를 함께 확인하세요.",
    "challenge": "gearMode에 문자 D를 넣어 `Mode: D`를 출력하세요.",
    "hint": "문자 하나는 작은따옴표로 감쌉니다.",
    "answer": "#include <iostream>\nint main() {\n    char gearMode = 'D';\n    std::cout << \"Mode: \" << gearMode << \"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 14,
    "part": "PART 2",
    "partTitle": "변수 · 자료형 · 연산",
    "title": "bool",
    "goal": "참/거짓 상태를 표현한다.",
    "concept": "<code>bool</code>은 <code>true</code> 또는 <code>false</code>를 저장합니다. 비교식의 결과도 bool입니다.",
    "code": "#include <iostream>\nint main() {\n    int speed = 120;\n    bool fast = speed > 100;\n    std::cout << std::boolalpha << fast << \"\\n\";\n}",
    "breakIt": "`speed > 100`을 `speed < 100`으로 바꾸세요.",
    "observe": "타입과 값이 어떻게 달라졌는지 출력 결과와 컴파일 메시지를 함께 확인하세요.",
    "challenge": "fuel이 10.0보다 작은지 나타내는 lowFuel을 만들고 출력하세요.",
    "hint": "비교식 자체를 bool에 넣으세요.",
    "answer": "#include <iostream>\nint main() {\n    double fuel = 8.5;\n    bool lowFuel = fuel < 10.0;\n    std::cout << std::boolalpha << lowFuel << \"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 15,
    "part": "PART 2",
    "partTitle": "변수 · 자료형 · 연산",
    "title": "auto",
    "goal": "초기값으로부터 타입을 추론한다.",
    "concept": "<code>auto</code>는 초기값을 보고 컴파일러가 타입을 결정하게 합니다. 타입이 없어지는 것이 아닙니다.",
    "code": "#include <iostream>\nint main() {\n    auto lap = 3;\n    auto time = 61.2;\n    std::cout << lap << \" \" << time << \"\\n\";\n}",
    "breakIt": "`auto lap;`처럼 초기값을 없애 보세요.",
    "observe": "타입과 값이 어떻게 달라졌는지 출력 결과와 컴파일 메시지를 함께 확인하세요.",
    "challenge": "auto로 평균속도 변수를 만들고 출력하세요.",
    "hint": "초기화 식이 타입 추론의 근거입니다.",
    "answer": "#include <iostream>\nint main() {\n    double distance = 150.0;\n    double hours = 2.0;\n    auto averageSpeed = distance / hours;\n    std::cout << averageSpeed << \"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 16,
    "part": "PART 2",
    "partTitle": "변수 · 자료형 · 연산",
    "title": "const",
    "goal": "바뀌면 안 되는 값에 의도를 부여한다.",
    "concept": "<code>const</code>는 초기화 후 값을 바꾸지 못하게 해 실수를 컴파일 단계에서 막습니다.",
    "code": "#include <iostream>\nint main() {\n    const double pi = 3.1415926535;\n    double radius = 2.0;\n    std::cout << pi * radius * radius << \"\\n\";\n}",
    "breakIt": "`pi = 3.0;`을 추가해 컴파일하세요.",
    "observe": "타입과 값이 어떻게 달라졌는지 출력 결과와 컴파일 메시지를 함께 확인하세요.",
    "challenge": "maxLaps를 const int 10으로 만들고 출력하세요.",
    "hint": "const 변수는 선언과 함께 초기화하세요.",
    "answer": "#include <iostream>\nint main() {\n    const int maxLaps = 10;\n    std::cout << maxLaps << \"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 17,
    "part": "PART 2",
    "partTitle": "변수 · 자료형 · 연산",
    "title": "산술 연산자",
    "goal": "+, -, *, /, %를 사용한다.",
    "concept": "기본 산술 연산자를 조합해 값을 계산합니다. <code>%</code>는 정수 나눗셈의 나머지입니다.",
    "code": "#include <iostream>\nint main() {\n    int totalSeconds = 125;\n    std::cout << totalSeconds / 60 << \" min \"\n              << totalSeconds % 60 << \" sec\\n\";\n}",
    "breakIt": "125를 120과 59로 각각 바꿔 몫과 나머지를 확인하세요.",
    "observe": "타입과 값이 어떻게 달라졌는지 출력 결과와 컴파일 메시지를 함께 확인하세요.",
    "challenge": "367초를 분과 초로 나누어 출력하세요.",
    "hint": "분은 / 60, 남은 초는 % 60 입니다.",
    "answer": "#include <iostream>\nint main() {\n    int total = 367;\n    std::cout << total / 60 << \" min \" << total % 60 << \" sec\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 18,
    "part": "PART 2",
    "partTitle": "변수 · 자료형 · 연산",
    "title": "연산 우선순위",
    "goal": "괄호로 계산 의도를 명확히 한다.",
    "concept": "곱셈·나눗셈은 덧셈·뺄셈보다 먼저 계산됩니다. 복잡한 식은 괄호로 의도를 명확히 하세요.",
    "code": "#include <iostream>\nint main() {\n    double a = 10;\n    double b = 20;\n    std::cout << (a + b) / 2 << \"\\n\";\n}",
    "breakIt": "괄호를 지워 `a + b / 2` 결과와 비교하세요.",
    "observe": "타입과 값이 어떻게 달라졌는지 출력 결과와 컴파일 메시지를 함께 확인하세요.",
    "challenge": "세 숫자 10, 20, 30의 평균을 계산하세요.",
    "hint": "합 전체를 괄호로 묶고 3.0으로 나누세요.",
    "answer": "#include <iostream>\nint main() {\n    double a=10, b=20, c=30;\n    std::cout << (a + b + c) / 3.0 << \"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 19,
    "part": "PART 2",
    "partTitle": "변수 · 자료형 · 연산",
    "title": "형 변환",
    "goal": "정수와 실수 계산에서 타입 변환을 의식한다.",
    "concept": "서로 다른 타입이 연산될 때 변환이 일어납니다. 의도를 명확히 할 때 <code>static_cast&lt;double&gt;</code>을 사용할 수 있습니다.",
    "code": "#include <iostream>\nint main() {\n    int total = 7;\n    int count = 2;\n    double average = static_cast<double>(total) / count;\n    std::cout << average << \"\\n\";\n}",
    "breakIt": "static_cast를 제거하고 `total / count` 결과를 double에 넣어 비교하세요.",
    "observe": "타입과 값이 어떻게 달라졌는지 출력 결과와 컴파일 메시지를 함께 확인하세요.",
    "challenge": "completed=3, total=8로 진행률 37.5%를 계산하세요.",
    "hint": "나누기 전에 한쪽을 double로 변환하고 100을 곱하세요.",
    "answer": "#include <iostream>\nint main() {\n    int completed = 3;\n    int total = 8;\n    double percent = static_cast<double>(completed) / total * 100.0;\n    std::cout << percent << \"%\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 20,
    "part": "PART 2",
    "partTitle": "변수 · 자료형 · 연산",
    "title": "입출력 미니 계산기",
    "goal": "변수·입력·연산·출력을 한 번에 묶는다.",
    "concept": "지금까지 배운 기본 요소를 하나의 작은 프로그램으로 연결합니다. 프로그램은 입력을 받아 계산하고 결과를 출력합니다.",
    "code": "#include <iostream>\nint main() {\n    double a=0, b=0;\n    std::cout << \"Two numbers: \";\n    std::cin >> a >> b;\n    std::cout << \"sum = \" << a + b << \"\\n\";\n    std::cout << \"avg = \" << (a + b) / 2.0 << \"\\n\";\n}",
    "breakIt": "두 번째 입력을 int로 바꾸고 2.5 같은 값을 넣어 입력 흐름을 관찰하세요.",
    "observe": "타입과 값이 어떻게 달라졌는지 출력 결과와 컴파일 메시지를 함께 확인하세요.",
    "challenge": "두 수의 합, 차, 곱, 평균을 모두 출력하는 계산기로 확장하세요.",
    "hint": "각 결과를 별도 cout으로 출력하면 됩니다.",
    "answer": "#include <iostream>\nint main() {\n    double a=0, b=0;\n    std::cin >> a >> b;\n    std::cout << \"sum: \" << a+b << \"\\n\";\n    std::cout << \"diff: \" << a-b << \"\\n\";\n    std::cout << \"product: \" << a*b << \"\\n\";\n    std::cout << \"average: \" << (a+b)/2.0 << \"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  }
]);