window.DRILLS=(window.DRILLS||[]).concat([
  {
    "id": 71,
    "part": "PART 8",
    "partTitle": "헤더 · 파일 · 프로젝트",
    "title": "헤더 파일",
    "goal": "공개할 선언을 .h에 둔다.",
    "concept": "헤더는 다른 소스 파일이 사용할 클래스·함수·타입의 <strong>선언/인터페이스</strong>를 제공하는 곳입니다.",
    "code": "// Car.h\n#pragma once\nclass Car {\npublic:\n    void accelerate();\n    int speed() const;\nprivate:\n    int speed_=0;\n};",
    "breakIt": "main.cpp에서 Car.h를 include하지 않고 Car 객체를 선언해 보세요.",
    "observe": "헤더만으로는 실행 파일이 되지 않습니다. 선언은 사용자가 함수의 형태를 알게 해줍니다.",
    "challenge": "Calculator.h에 `double average(double a,double b);` 선언을 작성하세요.",
    "hint": "헤더에는 함수 본문 없이 선언만 둘 수 있습니다.",
    "answer": "// Calculator.h\n#pragma once\ndouble average(double a,double b);",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 72,
    "part": "PART 8",
    "partTitle": "헤더 · 파일 · 프로젝트",
    "title": ".cpp 구현 파일",
    "goal": "헤더의 선언을 실제 코드로 정의한다.",
    "concept": "구현 파일은 헤더를 include하고 클래스 멤버나 함수의 실제 동작을 정의합니다. <code>Car::accelerate</code>의 <code>::</code>는 Car 범위의 함수라는 뜻입니다.",
    "code": "// Car.cpp\n#include \"Car.h\"\n\nvoid Car::accelerate() {\n    speed_ += 10;\n}\n\nint Car::speed() const {\n    return speed_;\n}",
    "breakIt": "Car::를 하나 지워 전역 함수와 멤버 함수 정의의 차이를 확인하세요.",
    "observe": "‘무엇이 존재하는가(선언)’와 ‘어떻게 동작하는가(정의)’를 파일별로 구분해 보세요.",
    "challenge": "Calculator.cpp에서 average를 구현하세요.",
    "hint": "헤더를 include한 뒤 선언과 정확히 같은 시그니처로 정의합니다.",
    "answer": "// Calculator.cpp\n#include \"Calculator.h\"\n\ndouble average(double a,double b) {\n    return (a+b)/2.0;\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 73,
    "part": "PART 8",
    "partTitle": "헤더 · 파일 · 프로젝트",
    "title": "여러 .cpp 컴파일",
    "goal": "각 번역 단위를 컴파일하고 링크한다.",
    "concept": "여러 .cpp가 있으면 모두 컴파일/링크 대상에 포함해야 합니다. main.cpp만 컴파일하면 다른 파일에 있는 정의를 찾지 못할 수 있습니다.",
    "code": "// main.cpp\n#include <iostream>\n#include \"Car.h\"\n\nint main() {\n    Car c;\n    c.accelerate();\n    std::cout << c.speed() << \"\\n\";\n}",
    "breakIt": "Car.cpp를 빼고 main.cpp만 컴파일해 링크 오류를 관찰하세요.",
    "observe": "컴파일은 성공했지만 링크에서 정의를 못 찾는 오류와 문법 컴파일 오류를 구분하세요.",
    "challenge": "main.cpp와 Calculator.cpp를 함께 컴파일해 average(10,20)를 출력하세요.",
    "hint": "명령에 두 .cpp 파일을 모두 적습니다.",
    "answer": "// main.cpp\n#include <iostream>\n#include \"Calculator.h\"\nint main(){ std::cout<<average(10,20)<<\"\\n\"; }",
    "compile": "clang++ -std=c++20 main.cpp Calculator.cpp -o app && ./app"
  },
  {
    "id": 74,
    "part": "PART 8",
    "partTitle": "헤더 · 파일 · 프로젝트",
    "title": "include guard / pragma once",
    "goal": "헤더가 한 번만 포함되도록 보호한다.",
    "concept": "같은 헤더가 여러 경로로 중복 포함될 수 있습니다. <code>#pragma once</code> 또는 전통적인 include guard로 중복 선언 문제를 막습니다.",
    "code": "// Telemetry.h\n#pragma once\n\nstruct Telemetry {\n    double speed;\n    double throttle;\n};",
    "breakIt": "#pragma once를 지운 뒤 동일 헤더를 두 번 include해 보고 타입 재정의 오류가 생기는 환경을 관찰하세요.",
    "observe": "‘무엇이 존재하는가(선언)’와 ‘어떻게 동작하는가(정의)’를 파일별로 구분해 보세요.",
    "challenge": "include guard 방식으로 Telemetry.h를 다시 작성하세요.",
    "hint": "#ifndef, #define, #endif 세 부분을 사용합니다.",
    "answer": "#ifndef TELEMETRY_H\n#define TELEMETRY_H\n\nstruct Telemetry {\n    double speed;\n    double throttle;\n};\n\n#endif",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 75,
    "part": "PART 8",
    "partTitle": "헤더 · 파일 · 프로젝트",
    "title": "내 namespace",
    "goal": "내 코드의 이름 충돌을 줄인다.",
    "concept": "프로젝트 코드도 namespace로 묶어 다른 라이브러리와 같은 이름이 충돌하는 것을 줄일 수 있습니다.",
    "code": "#include <iostream>\nnamespace gt {\n    double kmhToMps(double x){ return x/3.6; }\n}\nint main(){\n    std::cout<<gt::kmhToMps(180)<<\"\\n\";\n}",
    "breakIt": "gt::를 지우고 호출해 이름 검색이 어떻게 달라지는지 보세요.",
    "observe": "‘무엇이 존재하는가(선언)’와 ‘어떻게 동작하는가(정의)’를 파일별로 구분해 보세요.",
    "challenge": "landscape namespace 안에 area(w,h) 함수를 만들고 호출하세요.",
    "hint": "namespace 블록 안에 함수를 정의하고 `landscape::area`로 부릅니다.",
    "answer": "#include <iostream>\nnamespace landscape {\n    double area(double w,double h){ return w*h; }\n}\nint main(){ std::cout<<landscape::area(3,4)<<\"\\n\"; }",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 76,
    "part": "PART 8",
    "partTitle": "헤더 · 파일 · 프로젝트",
    "title": "ofstream",
    "goal": "프로그램 결과를 파일에 쓴다.",
    "concept": "<code>std::ofstream</code>은 출력 파일 스트림입니다. 파일을 열고 cout처럼 <code>&lt;&lt;</code>로 데이터를 쓸 수 있습니다.",
    "code": "#include <fstream>\nint main(){\n    std::ofstream out(\"laps.txt\");\n    out << \"1,60.2\\n\";\n    out << \"2,59.8\\n\";\n}",
    "breakIt": "파일 이름을 다른 경로로 바꾸거나 쓰기 권한이 없는 위치를 시도해 스트림 상태를 생각해 보세요.",
    "observe": "‘무엇이 존재하는가(선언)’와 ‘어떻게 동작하는가(정의)’를 파일별로 구분해 보세요.",
    "challenge": "speeds.txt에 80,100,120을 한 줄씩 저장하세요.",
    "hint": "ofstream을 만들고 for문으로 씁니다.",
    "answer": "#include <fstream>\n#include <vector>\nint main(){\n    std::ofstream out(\"speeds.txt\");\n    std::vector<int> v{80,100,120};\n    for(int x:v) out<<x<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 77,
    "part": "PART 8",
    "partTitle": "헤더 · 파일 · 프로젝트",
    "title": "ifstream",
    "goal": "텍스트 파일에서 데이터를 읽는다.",
    "concept": "<code>std::ifstream</code>은 입력 파일 스트림입니다. 파일도 cin과 비슷한 방식으로 값을 읽을 수 있습니다.",
    "code": "#include <fstream>\n#include <iostream>\nint main(){\n    std::ifstream in(\"laps.txt\");\n    int lap; double time;\n    while(in >> lap >> time)\n        std::cout<<lap<<\" \"<<time<<\"\\n\";\n}",
    "breakIt": "존재하지 않는 파일 이름을 넣고 `if(!in)`을 출력해 열기 실패를 확인하세요.",
    "observe": "‘무엇이 존재하는가(선언)’와 ‘어떻게 동작하는가(정의)’를 파일별로 구분해 보세요.",
    "challenge": "numbers.txt의 모든 double을 읽어 합계를 출력하세요.",
    "hint": "while(in >> x) 패턴을 사용하세요.",
    "answer": "#include <fstream>\n#include <iostream>\nint main(){\n    std::ifstream in(\"numbers.txt\");\n    double x=0,sum=0;\n    while(in>>x) sum+=x;\n    std::cout<<sum<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 78,
    "part": "PART 8",
    "partTitle": "헤더 · 파일 · 프로젝트",
    "title": "간단한 CSV 읽기",
    "goal": "쉼표로 구분된 한 줄을 분해한다.",
    "concept": "CSV는 단순해 보이지만 실제 규격은 인용부호 등 복잡할 수 있습니다. 여기서는 학습용으로 단순한 `lap,time` 형식만 다룹니다.",
    "code": "#include <iostream>\n#include <sstream>\n#include <string>\nint main(){\n    std::string line=\"2,59.8\";\n    std::stringstream ss(line);\n    std::string lap,time;\n    std::getline(ss,lap,',');\n    std::getline(ss,time,',');\n    std::cout<<lap<<\" \"<<time<<\"\\n\";\n}",
    "breakIt": "구분자 ','를 ';'로 바꿔 파싱 결과가 어떻게 달라지는지 보세요.",
    "observe": "‘무엇이 존재하는가(선언)’와 ‘어떻게 동작하는가(정의)’를 파일별로 구분해 보세요.",
    "challenge": "`speed,throttle,brake` 한 줄 `120.5,80,0`을 세 문자열로 분리하세요.",
    "hint": "getline을 세 번 호출하고 앞 두 번에는 ',' 구분자를 사용하세요.",
    "answer": "#include <iostream>\n#include <sstream>\n#include <string>\nint main(){\n    std::stringstream ss(\"120.5,80,0\");\n    std::string speed,throttle,brake;\n    std::getline(ss,speed,',');\n    std::getline(ss,throttle,',');\n    std::getline(ss,brake,',');\n    std::cout<<speed<<\" \"<<throttle<<\" \"<<brake<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 79,
    "part": "PART 8",
    "partTitle": "헤더 · 파일 · 프로젝트",
    "title": "std::filesystem",
    "goal": "파일과 경로를 표준 라이브러리로 다룬다.",
    "concept": "C++17 이후 <code>std::filesystem</code>은 파일 존재 여부, 경로, 디렉터리 등을 다루는 표준 도구입니다.",
    "code": "#include <filesystem>\n#include <iostream>\nint main(){\n    std::filesystem::path p=\"laps.csv\";\n    std::cout<<p.extension()<<\"\\n\";\n    std::cout<<std::filesystem::exists(p)<<\"\\n\";\n}",
    "breakIt": "파일을 만들기 전과 후 exists 결과를 비교하세요.",
    "observe": "‘무엇이 존재하는가(선언)’와 ‘어떻게 동작하는가(정의)’를 파일별로 구분해 보세요.",
    "challenge": "현재 경로의 파일 이름 `telemetry.csv`에서 stem과 extension을 각각 출력하세요.",
    "hint": "path의 stem(), extension()을 사용하세요.",
    "answer": "#include <filesystem>\n#include <iostream>\nint main(){\n    std::filesystem::path p=\"telemetry.csv\";\n    std::cout<<p.stem()<<\" \"<<p.extension()<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 80,
    "part": "PART 8",
    "partTitle": "헤더 · 파일 · 프로젝트",
    "title": "작은 프로젝트 구조",
    "goal": "역할별 파일을 나누는 기준을 익힌다.",
    "concept": "파일 분리는 무조건 많이 하는 것이 목적이 아닙니다. 공개 인터페이스, 구현, 프로그램 진입점처럼 <strong>변경 이유가 다른 코드</strong>를 분리합니다.",
    "code": "project/\n├── include/\n│   └── Telemetry.h\n├── src/\n│   ├── Telemetry.cpp\n│   └── main.cpp\n└── data/\n    └── laps.csv",
    "breakIt": "모든 코드를 main.cpp 하나에 넣었을 때와 역할별로 나눴을 때 수정 범위를 비교해 보세요.",
    "observe": "이 Drill은 코드 한 파일보다 디렉터리 구조 자체가 훈련 대상입니다.",
    "challenge": "Car.h, Car.cpp, main.cpp 세 파일로 Drill 71~73의 Car 예제를 실제 폴더에 구성하고 빌드하세요.",
    "hint": "헤더는 선언, Car.cpp는 구현, main.cpp는 사용에 집중합니다.",
    "answer": "// build example\n// Car.h      : class declaration\n// Car.cpp    : member definitions\n// main.cpp   : program entry point\n\n// compile:\n// clang++ -std=c++20 main.cpp Car.cpp -o car_app",
    "compile": "clang++ -std=c++20 main.cpp Car.cpp -o car_app && ./car_app"
  }
]);