window.DRILLS=(window.DRILLS||[]).concat([
  {
    "id": 51,
    "part": "PART 6",
    "partTitle": "표준 라이브러리",
    "title": "std::string",
    "goal": "문자열을 안전하고 편하게 다룬다.",
    "concept": "<code>std::string</code>은 문자열 저장·결합·길이 계산 등을 제공하는 표준 라이브러리 타입입니다.",
    "code": "#include <iostream>\n#include <string>\nint main(){\n    std::string track=\"Tsukuba\";\n    std::cout<<track<<\" \"<<track.size()<<\"\\n\";\n}",
    "breakIt": "#include <string>을 지워 컴파일해 보세요.",
    "observe": "직접 구현하려 하기 전에 표준 라이브러리가 어떤 문제를 이미 해결하는지 관찰하세요.",
    "challenge": "first와 last 문자열을 만들고 공백을 사이에 넣어 fullName을 만드세요.",
    "hint": "문자열은 +로 결합할 수 있습니다.",
    "answer": "#include <iostream>\n#include <string>\nint main(){\n    std::string first=\"C++\", last=\"Learner\";\n    std::string full=first+\" \"+last;\n    std::cout<<full<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 52,
    "part": "PART 6",
    "partTitle": "표준 라이브러리",
    "title": "getline",
    "goal": "공백이 포함된 한 줄을 입력받는다.",
    "concept": "<code>std::getline</code>은 공백을 포함한 한 줄 전체를 string에 읽습니다. <code>cin &gt;&gt;</code>와 차이를 체감하세요.",
    "code": "#include <iostream>\n#include <string>\nint main(){\n    std::string track;\n    std::getline(std::cin,track);\n    std::cout<<track<<\"\\n\";\n}",
    "breakIt": "getline 대신 `std::cin >> track`으로 바꾸고 `Nürburgring GP`처럼 공백 있는 입력을 넣어 보세요.",
    "observe": "직접 구현하려 하기 전에 표준 라이브러리가 어떤 문제를 이미 해결하는지 관찰하세요.",
    "challenge": "운전자 이름 한 줄을 입력받아 `Driver: 이름`으로 출력하세요.",
    "hint": "string 변수와 getline을 사용하세요.",
    "answer": "#include <iostream>\n#include <string>\nint main(){\n    std::string name;\n    std::getline(std::cin,name);\n    std::cout<<\"Driver: \"<<name<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 53,
    "part": "PART 6",
    "partTitle": "표준 라이브러리",
    "title": "std::vector",
    "goal": "크기가 변하는 연속 데이터 묶음을 사용한다.",
    "concept": "<code>std::vector</code>는 현대 C++에서 가장 먼저 떠올릴 만한 동적 배열입니다. 원소 수가 실행 중 변할 수 있습니다.",
    "code": "#include <iostream>\n#include <vector>\nint main(){\n    std::vector<double> times{60.1,59.9,61.0};\n    std::cout<<times.size()<<\" \"<<times[0]<<\"\\n\";\n}",
    "breakIt": "#include <vector>를 지워 보고, 빈 vector에서 [0] 접근도 별도로 시험하되 위험성을 이해하세요.",
    "observe": "직접 구현하려 하기 전에 표준 라이브러리가 어떤 문제를 이미 해결하는지 관찰하세요.",
    "challenge": "정수 속도 80, 100, 120, 140을 vector에 저장하고 크기를 출력하세요.",
    "hint": "중괄호 초기화 목록을 사용하세요.",
    "answer": "#include <iostream>\n#include <vector>\nint main(){\n    std::vector<int> speeds{80,100,120,140};\n    std::cout<<speeds.size()<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 54,
    "part": "PART 6",
    "partTitle": "표준 라이브러리",
    "title": "push_back",
    "goal": "vector 끝에 데이터를 추가한다.",
    "concept": "<code>push_back</code>은 vector 끝에 새 원소를 추가합니다. 입력 개수를 미리 모를 때 특히 유용합니다.",
    "code": "#include <iostream>\n#include <vector>\nint main(){\n    std::vector<double> times;\n    times.push_back(60.2);\n    times.push_back(59.8);\n    std::cout<<times.size()<<\"\\n\";\n}",
    "breakIt": "push_back 두 줄 사이에서 size를 출력해 크기 변화를 확인하세요.",
    "observe": "직접 구현하려 하기 전에 표준 라이브러리가 어떤 문제를 이미 해결하는지 관찰하세요.",
    "challenge": "3개의 속도를 cin으로 입력받아 빈 vector에 차례로 추가하세요.",
    "hint": "for문 안에서 입력 후 push_back 하세요.",
    "answer": "#include <iostream>\n#include <vector>\nint main(){\n    std::vector<int> speeds;\n    for(int i=0;i<3;++i){\n        int x; std::cin>>x;\n        speeds.push_back(x);\n    }\n    std::cout<<speeds.size()<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 55,
    "part": "PART 6",
    "partTitle": "표준 라이브러리",
    "title": "[]와 at()",
    "goal": "vector 원소 접근과 범위 검사를 비교한다.",
    "concept": "<code>[]</code>는 빠르지만 범위 검사를 하지 않습니다. <code>at()</code>은 잘못된 인덱스에서 예외를 발생시켜 오류를 드러냅니다.",
    "code": "#include <iostream>\n#include <vector>\nint main(){\n    std::vector<int> v{10,20,30};\n    std::cout<<v.at(1)<<\"\\n\";\n}",
    "breakIt": "v.at(10)을 실행해 어떤 오류가 나는지 확인하세요. v[10]과의 차이도 이해하되 잘못된 [] 접근은 정의되지 않은 동작입니다.",
    "observe": "직접 구현하려 하기 전에 표준 라이브러리가 어떤 문제를 이미 해결하는지 관찰하세요.",
    "challenge": "첫 원소와 마지막 원소를 front(), back()으로 출력하세요.",
    "hint": "vector에는 front()와 back() 멤버 함수가 있습니다.",
    "answer": "#include <iostream>\n#include <vector>\nint main(){\n    std::vector<int> v{10,20,30};\n    std::cout<<v.front()<<\" \"<<v.back()<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 56,
    "part": "PART 6",
    "partTitle": "표준 라이브러리",
    "title": "vector 순회",
    "goal": "vector의 모든 값을 처리한다.",
    "concept": "range-for는 vector의 모든 원소를 읽을 때 간단합니다. 수정하려면 참조를, 읽기만 하면 const 참조를 고려합니다.",
    "code": "#include <iostream>\n#include <vector>\nint main(){\n    std::vector<double> t{60.1,59.8,60.4};\n    for(double x:t) std::cout<<x<<\"\\n\";\n}",
    "breakIt": "double x를 double& x로 바꾸고 x += 1을 한 뒤 vector를 다시 출력하세요.",
    "observe": "직접 구현하려 하기 전에 표준 라이브러리가 어떤 문제를 이미 해결하는지 관찰하세요.",
    "challenge": "모든 속도를 3.6으로 나눠 m/s로 출력하세요.",
    "hint": "원본을 바꿀 필요가 없으면 값 또는 const 참조로 읽으세요.",
    "answer": "#include <iostream>\n#include <vector>\nint main(){\n    std::vector<double> speeds{36,72,108};\n    for(double x:speeds) std::cout<<x/3.6<<\" m/s\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 57,
    "part": "PART 6",
    "partTitle": "표준 라이브러리",
    "title": "std::sort",
    "goal": "정렬을 직접 구현하지 않고 표준 알고리즘을 쓴다.",
    "concept": "<code>std::sort</code>는 반복자 범위를 정렬합니다. ‘직접 정렬 알고리즘부터 만들기’보다 표준 도구를 먼저 찾는 습관을 익히세요.",
    "code": "#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){\n    std::vector<double> t{61.2,59.8,60.4};\n    std::sort(t.begin(),t.end());\n    for(double x:t) std::cout<<x<<\" \";\n}",
    "breakIt": "#include <algorithm>을 지워 컴파일하세요.",
    "observe": "직접 구현하려 하기 전에 표준 라이브러리가 어떤 문제를 이미 해결하는지 관찰하세요.",
    "challenge": "정수 vector를 큰 값부터 작은 값으로 정렬하세요.",
    "hint": "sort의 세 번째 인수로 `std::greater<>`를 사용할 수 있습니다.",
    "answer": "#include <algorithm>\n#include <functional>\n#include <iostream>\n#include <vector>\nint main(){\n    std::vector<int> v{3,9,1,7};\n    std::sort(v.begin(),v.end(),std::greater<>{});\n    for(int x:v) std::cout<<x<<\" \";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 58,
    "part": "PART 6",
    "partTitle": "표준 라이브러리",
    "title": "find와 count",
    "goal": "표준 알고리즘으로 검색하고 센다.",
    "concept": "<code>std::find</code>는 값을 찾고, <code>std::count</code>는 같은 값의 개수를 셉니다. 결과는 반복자 또는 개수입니다.",
    "code": "#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){\n    std::vector<int> gears{1,2,3,3,4};\n    auto it=std::find(gears.begin(),gears.end(),3);\n    std::cout<<(it!=gears.end())<<\" \"<<std::count(gears.begin(),gears.end(),3)<<\"\\n\";\n}",
    "breakIt": "찾는 값을 9로 바꿔 it가 end()가 되는지 확인하세요.",
    "observe": "직접 구현하려 하기 전에 표준 라이브러리가 어떤 문제를 이미 해결하는지 관찰하세요.",
    "challenge": "속도 vector에서 100이 몇 번 등장하는지 세세요.",
    "hint": "std::count를 사용하세요.",
    "answer": "#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){\n    std::vector<int> v{80,100,120,100,90};\n    std::cout<<std::count(v.begin(),v.end(),100)<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 59,
    "part": "PART 6",
    "partTitle": "표준 라이브러리",
    "title": "std::array",
    "goal": "크기가 컴파일 시 고정된 배열을 사용한다.",
    "concept": "<code>std::array&lt;T,N&gt;</code>는 크기가 고정되어 있지만 C 스타일 배열보다 표준 컨테이너 인터페이스를 제공합니다.",
    "code": "#include <array>\n#include <iostream>\nint main(){\n    std::array<double,3> sector{20.1,19.8,20.4};\n    for(double x:sector) std::cout<<x<<\" \";\n}",
    "breakIt": "array의 크기 3을 2로 바꾸되 초기값 3개를 그대로 두고 컴파일하세요.",
    "observe": "직접 구현하려 하기 전에 표준 라이브러리가 어떤 문제를 이미 해결하는지 관찰하세요.",
    "challenge": "4개 타이어 압력을 array로 저장하고 평균을 출력하세요.",
    "hint": "합계를 range-for로 구한 뒤 size()로 나누세요.",
    "answer": "#include <array>\n#include <iostream>\nint main(){\n    std::array<double,4> p{27.1,27.0,26.9,27.2};\n    double sum=0; for(double x:p) sum+=x;\n    std::cout<<sum/p.size()<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 60,
    "part": "PART 6",
    "partTitle": "표준 라이브러리",
    "title": "std::map",
    "goal": "키와 값을 연결해 저장한다.",
    "concept": "<code>std::map</code>은 key→value 관계를 표현합니다. 트랙 이름→최고기록처럼 의미 있는 키로 데이터를 찾을 수 있습니다.",
    "code": "#include <iostream>\n#include <map>\n#include <string>\nint main(){\n    std::map<std::string,double> best;\n    best[\"Tsukuba\"]=59.8;\n    best[\"Suzuka\"]=121.4;\n    std::cout<<best[\"Tsukuba\"]<<\"\\n\";\n}",
    "breakIt": "없는 키 `Monza`를 []로 읽은 뒤 map 크기가 변하는지 확인하세요. []가 새 항목을 만들 수 있음을 관찰합니다.",
    "observe": "직접 구현하려 하기 전에 표준 라이브러리가 어떤 문제를 이미 해결하는지 관찰하세요.",
    "challenge": "차량 이름→최고속도 int를 3개 저장하고 하나를 조회하세요.",
    "hint": "map<string,int>를 사용하세요.",
    "answer": "#include <iostream>\n#include <map>\n#include <string>\nint main(){\n    std::map<std::string,int> top{{\"MX-5\",210},{\"911\",310},{\"GT-R\",315}};\n    std::cout<<top.at(\"MX-5\")<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  }
]);