window.DRILLS=(window.DRILLS||[]).concat([
  {
    "id": 91,
    "part": "PART 10",
    "partTitle": "GT7 텔레메트리 미니 프로젝트",
    "title": "TelemetrySample 모델",
    "goal": "한 시점의 주행 데이터를 struct로 표현한다.",
    "concept": "실제 프로그램의 시작은 데이터를 어떤 형태로 표현할지 정하는 것입니다. 한 샘플에 시간·속도·스로틀·브레이크를 묶습니다.",
    "code": "#include <iostream>\nstruct TelemetrySample {\n    double time;\n    double speed;\n    double throttle;\n    double brake;\n};\nint main(){\n    TelemetrySample s{1.25,132.4,78.0,0.0};\n    std::cout<<s.time<<\" \"<<s.speed<<\"\\n\";\n}",
    "breakIt": "초기값의 순서를 speed와 time 반대로 넣어 타입은 맞지만 의미가 틀릴 수 있음을 확인하세요.",
    "observe": "이제 문법 하나보다 데이터 흐름을 봅니다: 입력 → 구조화 → 계산 → 결과 출력.",
    "challenge": "gear(int)와 steering(double)을 필드로 추가하고 샘플 하나를 출력하세요.",
    "hint": "struct 선언과 초기화 목록의 순서를 맞추세요.",
    "answer": "#include <iostream>\nstruct TelemetrySample {\n    double time,speed,throttle,brake;\n    int gear;\n    double steering;\n};\nint main(){\n    TelemetrySample s{1.25,132.4,78,0,4,-0.12};\n    std::cout<<s.speed<<\" gear \"<<s.gear<<\" steer \"<<s.steering<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 92,
    "part": "PART 10",
    "partTitle": "GT7 텔레메트리 미니 프로젝트",
    "title": "CSV 한 줄 → 샘플",
    "goal": "문자열 한 줄을 TelemetrySample로 변환한다.",
    "concept": "외부 데이터를 먼저 프로그램 내부 타입으로 변환하면 이후 분석 코드가 단순해집니다. 여기서는 학습용 단순 CSV만 다룹니다.",
    "code": "#include <iostream>\n#include <sstream>\n#include <string>\nstruct Sample{ double time,speed,throttle,brake; };\nSample parse(const std::string& line){\n    std::stringstream ss(line);\n    std::string a,b,c,d;\n    std::getline(ss,a,','); std::getline(ss,b,',');\n    std::getline(ss,c,','); std::getline(ss,d,',');\n    return {std::stod(a),std::stod(b),std::stod(c),std::stod(d)};\n}\nint main(){\n    auto s=parse(\"1.25,132.4,78,0\");\n    std::cout<<s.speed<<\"\\n\";\n}",
    "breakIt": "숫자가 아닌 문자열을 넣어 stod가 실패하는 경우를 관찰하세요.",
    "observe": "이제 문법 하나보다 데이터 흐름을 봅니다: 입력 → 구조화 → 계산 → 결과 출력.",
    "challenge": "샘플 문자열 두 줄을 각각 parse해 vector<Sample>에 push_back 하세요.",
    "hint": "vector를 include하고 parse 결과를 push_back 합니다.",
    "answer": "#include <iostream>\n#include <sstream>\n#include <string>\n#include <vector>\nstruct Sample{double time,speed,throttle,brake;};\nSample parse(const std::string& line){\n    std::stringstream ss(line); std::string a,b,c,d;\n    std::getline(ss,a,',');std::getline(ss,b,',');\n    std::getline(ss,c,',');std::getline(ss,d,',');\n    return {std::stod(a),std::stod(b),std::stod(c),std::stod(d)};\n}\nint main(){\n    std::vector<Sample> data;\n    data.push_back(parse(\"1.0,100,50,0\"));\n    data.push_back(parse(\"1.1,105,60,0\"));\n    std::cout<<data.size()<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 93,
    "part": "PART 10",
    "partTitle": "GT7 텔레메트리 미니 프로젝트",
    "title": "평균 속도",
    "goal": "vector<Sample>을 순회해 기본 통계를 계산한다.",
    "concept": "분석 함수는 원본 데이터를 읽고 하나의 명확한 결과를 반환하게 만들면 테스트하기 쉽습니다.",
    "code": "#include <iostream>\n#include <vector>\nstruct Sample{double speed;};\ndouble averageSpeed(const std::vector<Sample>& data){\n    if(data.empty()) return 0;\n    double sum=0;\n    for(const auto& s:data) sum+=s.speed;\n    return sum/data.size();\n}\nint main(){\n    std::vector<Sample> d{{100},{120},{140}};\n    std::cout<<averageSpeed(d)<<\"\\n\";\n}",
    "breakIt": "empty 체크를 지우고 빈 vector를 전달할 때 0으로 나누는 문제를 생각하세요.",
    "observe": "이제 문법 하나보다 데이터 흐름을 봅니다: 입력 → 구조화 → 계산 → 결과 출력.",
    "challenge": "maxSpeed 함수를 추가해 최고속도를 반환하세요.",
    "hint": "첫 원소를 초기 max로 두고 순회하되 빈 데이터도 처리하세요.",
    "answer": "#include <iostream>\n#include <vector>\nstruct Sample{double speed;};\ndouble maxSpeed(const std::vector<Sample>& d){\n    if(d.empty()) return 0;\n    double m=d.front().speed;\n    for(const auto& s:d) if(s.speed>m) m=s.speed;\n    return m;\n}\nint main(){ std::vector<Sample>d{{100},{150},{120}}; std::cout<<maxSpeed(d)<<\"\\n\"; }",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 94,
    "part": "PART 10",
    "partTitle": "GT7 텔레메트리 미니 프로젝트",
    "title": "최고 랩 찾기",
    "goal": "여러 Lap 중 가장 작은 시간을 찾는다.",
    "concept": "레이싱에서는 랩타임이 작을수록 좋습니다. 도메인 의미를 비교 연산에 정확히 반영해야 합니다.",
    "code": "#include <iostream>\n#include <vector>\nstruct Lap{int number; double time;};\nLap bestLap(const std::vector<Lap>& laps){\n    Lap best=laps.front();\n    for(const auto& l:laps) if(l.time<best.time) best=l;\n    return best;\n}\nint main(){\n    std::vector<Lap> laps{{1,61.2},{2,59.8},{3,60.1}};\n    auto b=bestLap(laps);\n    std::cout<<b.number<<\" \"<<b.time<<\"\\n\";\n}",
    "breakIt": "비교를 >로 바꿔 최악 랩이 선택되는지 확인하세요.",
    "observe": "이제 문법 하나보다 데이터 흐름을 봅니다: 입력 → 구조화 → 계산 → 결과 출력.",
    "challenge": "각 랩의 best 대비 delta를 출력하세요.",
    "hint": "먼저 best를 구한 뒤 `l.time - best.time`을 출력합니다.",
    "answer": "#include <iostream>\n#include <vector>\nstruct Lap{int number;double time;};\nint main(){\n    std::vector<Lap> v{{1,61.2},{2,59.8},{3,60.1}};\n    double best=v.front().time;\n    for(const auto& l:v) if(l.time<best) best=l.time;\n    for(const auto& l:v) std::cout<<\"L\"<<l.number<<\" +\"<<l.time-best<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 95,
    "part": "PART 10",
    "partTitle": "GT7 텔레메트리 미니 프로젝트",
    "title": "섹터 비교",
    "goal": "랩을 여러 구간으로 나눠 손실 구간을 찾는다.",
    "concept": "전체 랩타임만 보면 어디서 시간을 잃었는지 모릅니다. 섹터별 delta를 계산하면 개선 지점을 구체화할 수 있습니다.",
    "code": "#include <array>\n#include <iostream>\nint main(){\n    std::array<double,3> mine{20.5,19.9,20.8};\n    std::array<double,3> best{20.1,19.8,20.2};\n    for(std::size_t i=0;i<mine.size();++i)\n        std::cout<<\"S\"<<i+1<<\" delta \"<<mine[i]-best[i]<<\"\\n\";\n}",
    "breakIt": "mine과 best의 순서를 빼서 부호 의미가 어떻게 뒤집히는지 보세요.",
    "observe": "이제 문법 하나보다 데이터 흐름을 봅니다: 입력 → 구조화 → 계산 → 결과 출력.",
    "challenge": "가장 큰 양수 delta를 가진 섹터 번호를 찾으세요.",
    "hint": "worstDelta와 worstSector를 갱신합니다.",
    "answer": "#include <array>\n#include <iostream>\nint main(){\n    std::array<double,3> mine{20.5,19.9,20.8}, best{20.1,19.8,20.2};\n    double worst=-1; std::size_t sector=0;\n    for(std::size_t i=0;i<mine.size();++i){\n        double d=mine[i]-best[i];\n        if(d>worst){worst=d;sector=i;}\n    }\n    std::cout<<\"Improve S\"<<sector+1<<\" by \"<<worst<<\" s\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  }
]);