window.DRILLS=(window.DRILLS||[]).concat([
  {
    "id": 61,
    "part": "PART 7",
    "partTitle": "클래스와 객체",
    "title": "첫 class",
    "goal": "데이터와 동작을 하나의 타입으로 묶는다.",
    "concept": "클래스는 관련된 데이터와 그 데이터를 다루는 함수를 하나의 논리 단위로 묶는 사용자 정의 타입입니다.",
    "code": "#include <iostream>\nclass Car {\npublic:\n    int speed=0;\n    void accelerate(){ speed+=10; }\n};\nint main(){\n    Car car;\n    car.accelerate();\n    std::cout<<car.speed<<\"\\n\";\n}",
    "breakIt": "public:을 지워 main에서 speed와 accelerate 접근이 어떻게 막히는지 확인하세요.",
    "observe": "클래스는 타입의 설계이고 객체는 그 타입으로 만들어진 실제 인스턴스라는 점을 계속 구분하세요.",
    "challenge": "Counter 클래스를 만들고 value와 increment()를 넣으세요.",
    "hint": "Car 예시의 speed를 value로, accelerate를 increment로 바꿔 생각하세요.",
    "answer": "#include <iostream>\nclass Counter {\npublic:\n    int value=0;\n    void increment(){ ++value; }\n};\nint main(){ Counter c; c.increment(); std::cout<<c.value<<\"\\n\"; }",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 62,
    "part": "PART 7",
    "partTitle": "클래스와 객체",
    "title": "객체",
    "goal": "하나의 클래스에서 서로 독립적인 객체를 만든다.",
    "concept": "<code>Car a; Car b;</code>는 같은 설계도를 따르지만 각자 자신의 상태를 가진 두 객체입니다.",
    "code": "#include <iostream>\nclass Car { public: int speed=0; };\nint main(){\n    Car a,b;\n    a.speed=80;\n    b.speed=120;\n    std::cout<<a.speed<<\" \"<<b.speed<<\"\\n\";\n}",
    "breakIt": "a.speed만 바꾼 뒤 b.speed가 변하지 않는지 확인하세요.",
    "observe": "클래스는 타입의 설계이고 객체는 그 타입으로 만들어진 실제 인스턴스라는 점을 계속 구분하세요.",
    "challenge": "Driver 객체 me와 rival을 만들고 score를 서로 다르게 저장하세요.",
    "hint": "같은 클래스에서 객체 두 개를 선언합니다.",
    "answer": "#include <iostream>\nclass Driver { public: int score=0; };\nint main(){\n    Driver me,rival;\n    me.score=95; rival.score=88;\n    std::cout<<me.score<<\" \"<<rival.score<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 63,
    "part": "PART 7",
    "partTitle": "클래스와 객체",
    "title": "private와 public",
    "goal": "객체 내부 상태를 보호한다.",
    "concept": "<code>private</code> 멤버는 클래스 밖에서 직접 접근할 수 없습니다. 공개 함수로 상태 변경 규칙을 통제하는 것이 캡슐화의 핵심입니다.",
    "code": "#include <iostream>\nclass Car {\nprivate:\n    int speed=0;\npublic:\n    void accelerate(){ speed+=10; }\n    int getSpeed() const { return speed; }\n};\nint main(){ Car c; c.accelerate(); std::cout<<c.getSpeed()<<\"\\n\"; }",
    "breakIt": "main에서 `c.speed=999;`를 시도해 접근이 차단되는지 보세요.",
    "observe": "클래스는 타입의 설계이고 객체는 그 타입으로 만들어진 실제 인스턴스라는 점을 계속 구분하세요.",
    "challenge": "Battery 클래스를 만들고 level은 private, getLevel()과 charge()는 public으로 두세요.",
    "hint": "level을 직접 노출하지 말고 멤버 함수로 접근하세요.",
    "answer": "#include <iostream>\nclass Battery {\n    int level=0;\npublic:\n    void charge(){ if(level<100) level+=10; }\n    int getLevel() const { return level; }\n};\nint main(){ Battery b; b.charge(); std::cout<<b.getLevel()<<\"\\n\"; }",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 64,
    "part": "PART 7",
    "partTitle": "클래스와 객체",
    "title": "생성자",
    "goal": "객체가 만들어질 때 올바른 초기 상태를 만든다.",
    "concept": "생성자는 클래스와 같은 이름을 가지며 객체 생성 시 호출됩니다. 유효한 초기 상태를 강제하는 데 유용합니다.",
    "code": "#include <iostream>\nclass Car {\n    int speed;\npublic:\n    Car(int initialSpeed): speed(initialSpeed) {}\n    int getSpeed() const { return speed; }\n};\nint main(){ Car c(80); std::cout<<c.getSpeed()<<\"\\n\"; }",
    "breakIt": "Car c;처럼 인수 없이 생성해 컴파일하세요.",
    "observe": "클래스는 타입의 설계이고 객체는 그 타입으로 만들어진 실제 인스턴스라는 점을 계속 구분하세요.",
    "challenge": "Lap 클래스를 만들고 생성자로 number와 time을 받으세요.",
    "hint": "멤버 초기화 목록 `: number(n), time(t)`를 사용하세요.",
    "answer": "#include <iostream>\nclass Lap {\n    int number; double time;\npublic:\n    Lap(int n,double t):number(n),time(t){}\n    void show() const { std::cout<<number<<\" \"<<time<<\"\\n\"; }\n};\nint main(){ Lap l(2,60.4); l.show(); }",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 65,
    "part": "PART 7",
    "partTitle": "클래스와 객체",
    "title": "멤버 함수",
    "goal": "객체의 상태를 스스로 다루게 한다.",
    "concept": "멤버 함수는 특정 객체의 상태와 함께 동작합니다. 호출은 <code>object.function()</code> 형태입니다.",
    "code": "#include <iostream>\nclass Car {\n    int speed=0;\npublic:\n    void accelerate(int amount){ speed+=amount; }\n    void brake(int amount){ speed-=amount; if(speed<0) speed=0; }\n    int getSpeed() const{return speed;}\n};\nint main(){ Car c; c.accelerate(100); c.brake(30); std::cout<<c.getSpeed()<<\"\\n\"; }",
    "breakIt": "brake의 `if(speed<0)` 보호 코드를 지우고 200을 제동해 잘못된 음수 상태를 만들어 보세요.",
    "observe": "클래스는 타입의 설계이고 객체는 그 타입으로 만들어진 실제 인스턴스라는 점을 계속 구분하세요.",
    "challenge": "FuelTank에 add(double)와 use(double)를 만들어 fuel이 음수가 되지 않게 하세요.",
    "hint": "use 후 0보다 작아질 것 같으면 0으로 제한하세요.",
    "answer": "#include <iostream>\nclass FuelTank {\n    double fuel=0;\npublic:\n    void add(double x){ fuel+=x; }\n    void use(double x){ fuel = x>fuel ? 0 : fuel-x; }\n    double level() const{return fuel;}\n};\nint main(){ FuelTank f; f.add(20); f.use(7.5); std::cout<<f.level()<<\"\\n\"; }",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 66,
    "part": "PART 7",
    "partTitle": "클래스와 객체",
    "title": "const 멤버 함수",
    "goal": "객체 상태를 바꾸지 않는 함수를 표시한다.",
    "concept": "멤버 함수 뒤의 <code>const</code>는 이 함수가 객체의 관찰 가능한 상태를 바꾸지 않겠다는 약속입니다.",
    "code": "#include <iostream>\nclass Car {\n    int speed=90;\npublic:\n    int getSpeed() const { return speed; }\n};\nint main(){\n    const Car c;\n    std::cout<<c.getSpeed()<<\"\\n\";\n}",
    "breakIt": "getSpeed 뒤의 const를 지우고 const Car에서 호출해 보세요.",
    "observe": "클래스는 타입의 설계이고 객체는 그 타입으로 만들어진 실제 인스턴스라는 점을 계속 구분하세요.",
    "challenge": "Track 클래스에 const 멤버 함수 length()를 만드세요.",
    "hint": "읽기 전용 getter 뒤에 const를 붙입니다.",
    "answer": "#include <iostream>\nclass Track {\n    double meters=2045;\npublic:\n    double length() const { return meters; }\n};\nint main(){ const Track t; std::cout<<t.length()<<\"\\n\"; }",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 67,
    "part": "PART 7",
    "partTitle": "클래스와 객체",
    "title": "this",
    "goal": "현재 객체 자신을 가리킨다.",
    "concept": "멤버 함수 안의 <code>this</code>는 현재 함수를 호출한 객체를 가리키는 포인터입니다. 이름 충돌을 명확히 할 때도 볼 수 있습니다.",
    "code": "#include <iostream>\nclass Car {\n    int speed=0;\npublic:\n    void setSpeed(int speed){ this->speed=speed; }\n    int getSpeed() const{return speed;}\n};\nint main(){ Car c; c.setSpeed(123); std::cout<<c.getSpeed()<<\"\\n\"; }",
    "breakIt": "`this->`를 지우고 `speed=speed;`로 바꿔 매개변수와 멤버 이름 충돌을 관찰하세요.",
    "observe": "클래스는 타입의 설계이고 객체는 그 타입으로 만들어진 실제 인스턴스라는 점을 계속 구분하세요.",
    "challenge": "Driver 클래스에서 setName의 매개변수와 멤버를 둘 다 name으로 두고 this를 사용하세요.",
    "hint": "`this->name = name;` 형태입니다.",
    "answer": "#include <iostream>\n#include <string>\nclass Driver {\n    std::string name;\npublic:\n    void setName(std::string name){ this->name=name; }\n    void show() const{ std::cout<<name<<\"\\n\"; }\n};\nint main(){ Driver d; d.setName(\"Kim\"); d.show(); }",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 68,
    "part": "PART 7",
    "partTitle": "클래스와 객체",
    "title": "struct와 class",
    "goal": "두 문법의 기본 접근 차이를 이해한다.",
    "concept": "C++에서 struct와 class는 매우 비슷합니다. 핵심 문법 차이는 기본 접근이 struct는 public, class는 private라는 점입니다.",
    "code": "#include <iostream>\nstruct Point { double x=0, y=0; };\nint main(){\n    Point p{3,4};\n    std::cout<<p.x<<\" \"<<p.y<<\"\\n\";\n}",
    "breakIt": "struct를 class로만 바꾸고 public을 추가하지 않은 채 접근해 보세요.",
    "observe": "클래스는 타입의 설계이고 객체는 그 타입으로 만들어진 실제 인스턴스라는 점을 계속 구분하세요.",
    "challenge": "단순 데이터 묶음 TelemetrySample을 struct로 만들고 speed, throttle, brake를 넣으세요.",
    "hint": "행동보다 데이터 묶음 성격이 강하면 struct가 자연스러울 수 있습니다.",
    "answer": "#include <iostream>\nstruct TelemetrySample {\n    double speed;\n    double throttle;\n    double brake;\n};\nint main(){\n    TelemetrySample s{120,80,0};\n    std::cout<<s.speed<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 69,
    "part": "PART 7",
    "partTitle": "클래스와 객체",
    "title": "enum class",
    "goal": "정해진 선택지를 타입 안전하게 표현한다.",
    "concept": "<code>enum class</code>는 서로 관련된 명명된 값 집합을 만듭니다. 단순 숫자보다 의미가 분명하고 이름 충돌을 줄입니다.",
    "code": "#include <iostream>\nenum class Mode { Practice, Race, TimeTrial };\nint main(){\n    Mode mode=Mode::Race;\n    if(mode==Mode::Race) std::cout<<\"RACE\\n\";\n}",
    "breakIt": "`Mode::Race`에서 `Mode::`를 지워 범위 지정이 필요한지 확인하세요.",
    "observe": "클래스는 타입의 설계이고 객체는 그 타입으로 만들어진 실제 인스턴스라는 점을 계속 구분하세요.",
    "challenge": "Weather를 Dry, Wet, Snow로 정의하고 Wet일 때 메시지를 출력하세요.",
    "hint": "enum class Weather를 선언하고 Weather::Wet로 비교하세요.",
    "answer": "#include <iostream>\nenum class Weather { Dry,Wet,Snow };\nint main(){\n    Weather w=Weather::Wet;\n    if(w==Weather::Wet) std::cout<<\"Use wet setup\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 70,
    "part": "PART 7",
    "partTitle": "클래스와 객체",
    "title": "클래스로 랩 모델링",
    "goal": "데이터와 규칙을 하나의 객체로 설계한다.",
    "concept": "객체 설계에서는 ‘어떤 데이터를 가지고 어떤 동작을 책임질 것인가’를 결정합니다. 외부가 내부 데이터를 함부로 바꾸지 않게 인터페이스를 만드세요.",
    "code": "#include <iostream>\nclass Lap {\n    int number;\n    double time;\npublic:\n    Lap(int n,double t):number(n),time(t){}\n    bool fasterThan(const Lap& other) const { return time<other.time; }\n    double getTime() const { return time; }\n};\nint main(){\n    Lap a(1,60.2), b(2,59.8);\n    std::cout<<std::boolalpha<<b.fasterThan(a)<<\"\\n\";\n}",
    "breakIt": "fasterThan의 <를 >로 바꿔 의미가 뒤집히는지 확인하세요.",
    "observe": "클래스는 타입의 설계이고 객체는 그 타입으로 만들어진 실제 인스턴스라는 점을 계속 구분하세요.",
    "challenge": "Lap에 deltaTo(const Lap&)를 추가해 두 랩의 시간 차이를 반환하세요.",
    "hint": "현재 객체의 time에서 other.getTime()을 빼면 됩니다.",
    "answer": "#include <iostream>\nclass Lap {\n    int number; double time;\npublic:\n    Lap(int n,double t):number(n),time(t){}\n    double getTime() const{return time;}\n    double deltaTo(const Lap& other) const{return time-other.time;}\n};\nint main(){ Lap a(1,60.2),b(2,59.8); std::cout<<b.deltaTo(a)<<\"\\n\"; }",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  }
]);