window.DRILLS=(window.DRILLS||[]).concat([
  {
    "id": 81,
    "part": "PART 9",
    "partTitle": "현대 C++ 핵심",
    "title": "포인터 기초",
    "goal": "주소를 저장하는 변수와 역참조를 이해한다.",
    "concept": "포인터는 객체의 메모리 주소를 저장합니다. <code>&amp;x</code>는 주소, <code>*p</code>는 그 주소가 가리키는 값을 뜻합니다.",
    "code": "#include <iostream>\nint main(){\n    int speed=80;\n    int* p=&speed;\n    std::cout<<*p<<\"\\n\";\n    *p=100;\n    std::cout<<speed<<\"\\n\";\n}",
    "breakIt": "p를 다른 int 변수의 주소로 바꿔 *p가 무엇을 가리키는지 확인하세요.",
    "observe": "소유권·수명·null 가능성처럼 ‘값 외의 상태’를 코드가 얼마나 명확히 표현하는지 보세요.",
    "challenge": "double throttle=50을 만들고 포인터를 통해 75로 변경하세요.",
    "hint": "double* p=&throttle; 후 *p=75 입니다.",
    "answer": "#include <iostream>\nint main(){\n    double throttle=50;\n    double* p=&throttle;\n    *p=75;\n    std::cout<<throttle<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 82,
    "part": "PART 9",
    "partTitle": "현대 C++ 핵심",
    "title": "nullptr",
    "goal": "아무 객체도 가리키지 않는 포인터를 표현한다.",
    "concept": "<code>nullptr</code>는 포인터가 유효한 객체를 가리키지 않음을 명확히 표현합니다. 역참조하기 전에 유효성을 검사해야 합니다.",
    "code": "#include <iostream>\nint main(){\n    int* p=nullptr;\n    if(p) std::cout<<*p<<\"\\n\";\n    else std::cout<<\"no value\\n\";\n}",
    "breakIt": "if 검사를 지우고 nullptr을 역참조하는 코드는 왜 위험한지 이해하세요. 실제 실행은 크래시할 수 있습니다.",
    "observe": "소유권·수명·null 가능성처럼 ‘값 외의 상태’를 코드가 얼마나 명확히 표현하는지 보세요.",
    "challenge": "int value=42를 만들고 처음엔 nullptr이던 p가 value를 가리키게 한 뒤 출력하세요.",
    "hint": "`p=&value;` 후 검사하고 역참조합니다.",
    "answer": "#include <iostream>\nint main(){\n    int value=42;\n    int* p=nullptr;\n    p=&value;\n    if(p) std::cout<<*p<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 83,
    "part": "PART 9",
    "partTitle": "현대 C++ 핵심",
    "title": "참조 vs 포인터",
    "goal": "두 간접 접근 방식의 차이를 구분한다.",
    "concept": "참조는 보통 반드시 유효한 객체의 별칭으로 사용하고, 포인터는 nullptr이나 다른 대상을 가리키는 상태를 표현할 수 있습니다.",
    "code": "#include <iostream>\nint main(){\n    int speed=80;\n    int& ref=speed;\n    int* ptr=&speed;\n    ref=90;\n    *ptr=100;\n    std::cout<<speed<<\"\\n\";\n}",
    "breakIt": "포인터는 nullptr로 바꿀 수 있지만 참조를 ‘아무것도 참조하지 않게’ 만들 수 있는지 생각하세요.",
    "observe": "소유권·수명·null 가능성처럼 ‘값 외의 상태’를 코드가 얼마나 명확히 표현하는지 보세요.",
    "challenge": "값을 반드시 수정해야 하는 함수는 int&, 선택적으로 값이 있을 수도 있는 함수는 int*를 받는 예를 각각 작성하세요.",
    "hint": "참조 함수는 바로 수정, 포인터 함수는 nullptr 검사 후 수정하세요.",
    "answer": "#include <iostream>\nvoid required(int& x){ ++x; }\nvoid optional(int* x){ if(x) ++(*x); }\nint main(){\n    int a=1,b=1;\n    required(a); optional(&b); optional(nullptr);\n    std::cout<<a<<\" \"<<b<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 84,
    "part": "PART 9",
    "partTitle": "현대 C++ 핵심",
    "title": "raw new를 피하는 이유",
    "goal": "동적 메모리와 수동 delete의 부담을 이해한다.",
    "concept": "<code>new/delete</code>를 이해하는 것은 필요하지만 일반 애플리케이션 코드에서는 컨테이너와 스마트 포인터로 소유권을 표현하는 편이 안전합니다.",
    "code": "#include <iostream>\nint main(){\n    int* p=new int(42);\n    std::cout<<*p<<\"\\n\";\n    delete p;\n    p=nullptr;\n}",
    "breakIt": "delete를 빼면 코드가 당장 출력은 되더라도 메모리 누수 가능성이 생기는 이유를 생각하세요.",
    "observe": "소유권·수명·null 가능성처럼 ‘값 외의 상태’를 코드가 얼마나 명확히 표현하는지 보세요.",
    "challenge": "같은 목적을 다음 Drill의 unique_ptr로 바꾸기 전에 raw pointer의 ‘누가 delete할 책임이 있는가’를 한 문장으로 적으세요.",
    "hint": "소유권이 코드에 명확히 드러나지 않으면 delete 책임을 추적하기 어려워집니다.",
    "answer": "// 핵심 메모\n// raw owning pointer:\n//   누가 delete 하는지 사람이 추적해야 한다.\n// modern C++:\n//   소유권을 RAII 객체로 표현하는 것을 우선한다.",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 85,
    "part": "PART 9",
    "partTitle": "현대 C++ 핵심",
    "title": "std::unique_ptr",
    "goal": "단독 소유권을 자동 수명 관리로 표현한다.",
    "concept": "<code>std::unique_ptr</code>는 하나의 소유자가 객체를 관리하며 범위를 벗어나면 자동으로 정리합니다.",
    "code": "#include <iostream>\n#include <memory>\nint main(){\n    auto p=std::make_unique<int>(42);\n    std::cout<<*p<<\"\\n\";\n}",
    "breakIt": "unique_ptr을 `auto q=p;`로 복사하려 해 보세요. 단독 소유권 때문에 복사가 막힙니다.",
    "observe": "소유권·수명·null 가능성처럼 ‘값 외의 상태’를 코드가 얼마나 명확히 표현하는지 보세요.",
    "challenge": "string을 unique_ptr로 만들고 값을 출력하세요.",
    "hint": "`std::make_unique<std::string>(...)`를 사용하고 <string>을 include 하세요.",
    "answer": "#include <iostream>\n#include <memory>\n#include <string>\nint main(){\n    auto p=std::make_unique<std::string>(\"GT7\");\n    std::cout<<*p<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 86,
    "part": "PART 9",
    "partTitle": "현대 C++ 핵심",
    "title": "RAII",
    "goal": "자원 수명을 객체 수명에 묶는다.",
    "concept": "RAII는 파일·메모리·락 같은 자원을 객체의 생성과 파괴에 묶는 C++ 핵심 설계입니다. scope를 벗어나면 정리되는 타입을 선호합니다.",
    "code": "#include <fstream>\nint main(){\n    std::ofstream out(\"log.txt\");\n    out<<\"session start\\n\";\n} // out의 소멸자가 파일 자원을 정리",
    "breakIt": "명시적 close 없이도 scope 종료 시 정리되는 점과, 수동 자원 관리와의 차이를 생각하세요.",
    "observe": "소유권·수명·null 가능성처럼 ‘값 외의 상태’를 코드가 얼마나 명확히 표현하는지 보세요.",
    "challenge": "중괄호 scope 안에서 파일을 열어 한 줄 쓰고 scope 밖으로 나오는 예를 작성하세요.",
    "hint": "ofstream 자체가 RAII 객체입니다.",
    "answer": "#include <fstream>\nint main(){\n    {\n        std::ofstream out(\"log.txt\");\n        out<<\"inside scope\\n\";\n    }\n    // 여기서는 out이 이미 소멸됨\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 87,
    "part": "PART 9",
    "partTitle": "현대 C++ 핵심",
    "title": "std::optional",
    "goal": "값이 없을 수도 있음을 타입으로 표현한다.",
    "concept": "<code>std::optional&lt;T&gt;</code>은 ‘T 값이 있거나 없음’을 명시합니다. 마법의 -1 같은 특별값보다 의도가 분명합니다.",
    "code": "#include <iostream>\n#include <optional>\nstd::optional<double> bestLap(bool hasData){\n    if(!hasData) return std::nullopt;\n    return 59.8;\n}\nint main(){\n    auto v=bestLap(true);\n    if(v) std::cout<<*v<<\"\\n\";\n}",
    "breakIt": "bestLap(false)로 바꾸고 if 검사가 값을 안전하게 막는지 보세요.",
    "observe": "소유권·수명·null 가능성처럼 ‘값 외의 상태’를 코드가 얼마나 명확히 표현하는지 보세요.",
    "challenge": "양수일 때만 값을 반환하는 positive(double) 함수를 optional<double>로 만드세요.",
    "hint": "0 이하이면 std::nullopt를 반환합니다.",
    "answer": "#include <iostream>\n#include <optional>\nstd::optional<double> positive(double x){\n    if(x<=0) return std::nullopt;\n    return x;\n}\nint main(){ if(auto v=positive(3.2)) std::cout<<*v<<\"\\n\"; }",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 88,
    "part": "PART 9",
    "partTitle": "현대 C++ 핵심",
    "title": "람다",
    "goal": "짧은 동작을 필요한 위치에서 함수 객체로 만든다.",
    "concept": "람다는 작은 함수를 그 자리에서 만들 수 있게 합니다. 표준 알고리즘의 조건이나 정렬 기준과 잘 어울립니다.",
    "code": "#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){\n    std::vector<int> v{80,120,90,150};\n    auto fast=std::count_if(v.begin(),v.end(),\n        [](int x){ return x>=100; });\n    std::cout<<fast<<\"\\n\";\n}",
    "breakIt": "람다 조건을 x>=100에서 x<100으로 바꿔 결과를 비교하세요.",
    "observe": "소유권·수명·null 가능성처럼 ‘값 외의 상태’를 코드가 얼마나 명확히 표현하는지 보세요.",
    "challenge": "랩타임 vector에서 60초 미만인 값의 개수를 count_if와 람다로 구하세요.",
    "hint": "조건은 `t < 60.0`입니다.",
    "answer": "#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){\n    std::vector<double> t{59.8,60.2,58.9,61.0};\n    auto n=std::count_if(t.begin(),t.end(),[](double x){return x<60.0;});\n    std::cout<<n<<\"\\n\";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 89,
    "part": "PART 9",
    "partTitle": "현대 C++ 핵심",
    "title": "ranges",
    "goal": "데이터 처리 의도를 더 직접적으로 표현한다.",
    "concept": "C++20 ranges는 알고리즘과 뷰를 더 조합하기 쉽게 만듭니다. 처음에는 <code>std::ranges::sort</code>처럼 간단한 것부터 익히세요.",
    "code": "#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){\n    std::vector<int> v{4,1,3,2};\n    std::ranges::sort(v);\n    for(int x:v) std::cout<<x<<\" \";\n}",
    "breakIt": "`-std=c++17`로 컴파일해 C++20 기능 사용 시 표준 버전의 의미를 확인하세요.",
    "observe": "소유권·수명·null 가능성처럼 ‘값 외의 상태’를 코드가 얼마나 명확히 표현하는지 보세요.",
    "challenge": "std::ranges::sort로 랩타임을 오름차순 정렬하세요.",
    "hint": "<algorithm>과 C++20 옵션을 사용하세요.",
    "answer": "#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){\n    std::vector<double> t{60.3,59.7,61.1};\n    std::ranges::sort(t);\n    for(double x:t) std::cout<<x<<\" \";\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  },
  {
    "id": 90,
    "part": "PART 9",
    "partTitle": "현대 C++ 핵심",
    "title": "예외 기초",
    "goal": "정상 흐름과 처리할 수 없는 오류를 구분한다.",
    "concept": "예외는 함수가 정상 결과를 만들 수 없는 상황을 호출자에게 전달하는 한 방법입니다. 남용하지 말고 오류 처리 정책을 명확히 하세요.",
    "code": "#include <iostream>\n#include <stdexcept>\ndouble divide(double a,double b){\n    if(b==0) throw std::invalid_argument(\"division by zero\");\n    return a/b;\n}\nint main(){\n    try {\n        std::cout<<divide(10,0)<<\"\\n\";\n    } catch(const std::exception& e) {\n        std::cout<<\"error: \"<<e.what()<<\"\\n\";\n    }\n}",
    "breakIt": "try/catch를 지우고 예외가 처리되지 않을 때 프로그램이 어떻게 끝나는지 확인하세요.",
    "observe": "소유권·수명·null 가능성처럼 ‘값 외의 상태’를 코드가 얼마나 명확히 표현하는지 보세요.",
    "challenge": "negative speed를 받으면 invalid_argument를 던지는 validateSpeed 함수를 만드세요.",
    "hint": "x<0이면 throw 하고, 아니면 그대로 반환해도 됩니다.",
    "answer": "#include <iostream>\n#include <stdexcept>\ndouble validateSpeed(double x){\n    if(x<0) throw std::invalid_argument(\"negative speed\");\n    return x;\n}\nint main(){\n    try { std::cout<<validateSpeed(-1)<<\"\\n\"; }\n    catch(const std::exception& e){ std::cout<<e.what()<<\"\\n\"; }\n}",
    "compile": "clang++ -std=c++20 main.cpp -o main && ./main"
  }
]);